In [1]:
import gym
import numpy as np
import pandas as pd
import time

from aprl.agents.monte_carlo import MujocoResettableWrapper, MonteCarloParallel, receding_horizon
from experiments.common import set_seeds, make_env, fit_ilqr, \
                               on_iteration, receding, multi_evaluate

Logging to /tmp/openai-2019-02-09-15-06-16-550422


WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'


Choosing the latest nvidia driver: /usr/lib/nvidia-396, among ['/usr/lib/nvidia-375', '/usr/lib/nvidia-396']
Choosing the latest nvidia driver: /usr/lib/nvidia-396, among ['/usr/lib/nvidia-375', '/usr/lib/nvidia-396']


In [2]:
def make_env(env_name, seed):
    env = gym.make(env_name)
    env = MujocoResettableWrapper(env.unwrapped)
    env.seed(seed)
    return env

In [3]:
env_name = 'HalfCheetah-v2'
seed = 42

In [4]:
env = make_env(env_name, seed=seed)
env_fns = [lambda: make_env(env_name, seed=seed) for _ in range(24)]
mc = MonteCarloParallel(env_fns, 10, 4096, seed=seed)

In [6]:
rews = []
for a, ob, rew, done, info in receding_horizon(mc, env):
    print(a, ob, rew, done, info)
    rews.append(rew)
    env.render()
    if len(rews) == 100:
        break
print(sum(rews))

[ 0.28052264 -0.32534343 -0.928166    0.4588289  -0.34748146  0.3822738 ] [-5.51758820e-02  6.99789259e-03  1.28922837e-01 -1.31921270e-01
 -3.66888241e-01  1.81502306e-01 -1.73908638e-01  9.86375807e-02
  3.74791791e-01 -1.05082805e+00  1.06452323e-01  2.81086345e+00
 -2.96312564e+00 -8.51698950e+00  4.72367972e+00 -3.83688925e+00
  2.72213896e+00] 0.15410960966400017 False {'reward_run': 0.3064530139570605, 'reward_ctrl': -0.1523434042930603}
Creating window glfw
[-0.21367602  0.3087172   0.8297908   0.3022408   0.5734391  -0.6330225 ] [-0.11033552  0.01005326 -0.06484349  0.12392352 -0.05396049  0.23823165
  0.08481889 -0.08603672  0.11830505 -0.86583967  0.82959954 -6.78707874
  7.29307817  8.00430199 -0.7094136   8.36608467 -6.38684437] -0.06638576718933382 False {'reward_run': 0.09865582254760467, 'reward_ctrl': -0.1650415897369385}
[ 0.6346947   0.45434523 -0.7420486   0.7642606   0.02479173  0.00497717] [-0.13647269 -0.01088365  0.06630236  0.2565848  -0.20459108  0.47878851
  

[-0.38026655 -0.93757147 -0.29685116 -0.721809   -0.08583108 -0.8451082 ] [-0.02163063  1.0035037  -0.09683107 -0.4066089   0.05991268  0.45111013
 -0.17872833 -0.54549761  2.10937113  0.80223931  0.58298281 -2.50716021
 -9.96105209 -7.76706109 -4.47092773  7.39374951  1.42226878] 1.7835121464037562 False {'reward_run': 2.018946821620431, 'reward_ctrl': -0.23543467521667483}
[-0.95378274  0.39424422  0.6049372  -0.9367999  -0.27163687  0.49633265] [  0.04092879   0.92911215  -0.58101894  -0.15741386   0.12401957
   0.11314982   0.24588714  -0.06832692   1.41858046   1.23963377
  -2.06468362 -10.71154802   8.34441283   4.71589629  -7.45090929
   7.88869472  14.50430516] 1.2902655724074603 False {'reward_run': 1.5531461123015644, 'reward_ctrl': -0.26288053989410404}
[-0.18184721 -0.66469383 -0.23460552 -0.7508561   0.72937405  0.24471036] [ 0.0938985   0.92303878 -0.37941794 -0.4200362  -0.0492669  -0.31407406
  0.65169182  0.52517424  2.66616777  0.76623436  0.35492551  6.39422211
 -6.1

[-0.6925772   0.30345502 -0.0737414  -0.63482827  0.67298055 -0.14788723] [-0.05597233  0.837384    0.09639582  0.36419529  0.15157866  0.3253028
  0.40153001 -0.40458745  2.38937601  0.81445356  0.8136771  -5.32828904
  4.63124878  3.45626099 -6.37781074 12.74362315  1.18192625] 2.1588048700679807 False {'reward_run': 2.3043015007366208, 'reward_ctrl': -0.14549663066864013}
[-0.01120393 -0.0336653  -0.9476158  -0.90407205  0.8669041   0.40235385] [ 5.88542806e-04  9.47514844e-01 -4.22379225e-02  1.32410619e-01
 -2.69873126e-01 -1.77699157e-01  8.89360834e-01  7.22194461e-02
  2.74339742e+00  1.14508145e+00  2.88553469e+00 -1.47694169e+00
 -8.51355779e+00 -1.16527387e+01 -9.33137629e+00  5.59512385e+00
  1.32449118e+01] 2.413573179070488 False {'reward_run': 2.676572379891411, 'reward_ctrl': -0.2629992008209229}
[ 0.7505495   0.711031    0.29796907  0.9787493  -0.73623884  0.32821447] [-2.03301418e-02  1.04281362e+00  9.16706481e-02  7.11647379e-02
 -1.87983242e-01  2.51932949e-01 -6.9

[ 0.39484057  0.42716363  0.08289728  0.5273808  -0.16535738 -0.3072863 ] [-5.20014862e-04  1.03322471e+00  2.32789935e-01  1.66628699e-02
  1.07829064e-01  5.90605744e-01 -1.63639307e-02  2.02601576e-01
  2.69418436e+00 -9.39826683e-01 -3.00115886e+00  5.75881440e-01
  1.37053991e+01  1.30833218e+00  5.23271211e+00 -2.85553936e+00
 -4.77006823e+00] 2.7744105417560867 False {'reward_run': 2.8489243645500473, 'reward_ctrl': -0.07451382279396057}
[ 0.3349569  -0.86645806  0.0687355   0.7754481  -0.45243922 -0.75971633] [-0.03937491  0.98170183  0.33274573 -0.05640921  0.12237552  0.69222127
 -0.17935152 -0.23903627  3.43432476 -0.66328296 -0.04740543  1.34310211
 -7.86469299 -0.45409894 -0.37202893 -2.85716193 -9.67033137] 2.983267718837781 False {'reward_run': 3.2083537402611206, 'reward_ctrl': -0.22508602142333986}
[-0.76688814 -0.622937    0.9945258  -0.7967485   0.5388574   0.748474  ] [-7.82260634e-03  9.80180147e-01 -6.23545908e-02 -3.15089465e-01
  4.82744502e-01  1.72071975e-01  

[ 0.8946917   0.99618345  0.25870213  0.09212986  0.6011191  -0.90872526] [ 0.11485668  1.44993396  0.51318003  0.5669206   0.10316197 -0.20344004
  0.56136067 -0.23259819  2.76187828 -0.56616475 -1.50080253 16.76117246
  5.62143373  3.98398082  9.4081535  -4.80137496 -1.78067455] 2.6685501566951872 False {'reward_run': 2.9740896931713223, 'reward_ctrl': -0.3055395364761353}
[ 0.83311474 -0.42822668 -0.46103916  0.6689549  -0.7668955   0.1469769 ] [  0.08742576   1.5291007    0.87139079   0.17098086   0.02297985
   0.42715337  -0.27403251  -0.09375382   3.3507433   -0.32275482
   3.5334085   -1.02671663 -11.84101102  -4.5064684   11.09309953
 -16.80540069   4.58218661] 2.8727734284431663 False {'reward_run': 3.087498112204763, 'reward_ctrl': -0.2147246837615967}
[ 0.5745408   0.8015239   0.32536456 -0.02560787  0.43508026  0.70546246] [  0.11443768   1.68283639   0.38812801   0.13655676   0.08228791
   0.3113628   -0.20748707   0.25827477   4.03790653   0.70269628
   2.21534898 -11.189

[-0.7741996   0.4719672   0.09012021 -0.531585   -0.4050021   0.4728505 ] [-0.41706058  3.15571001 -0.62173814  0.09331058 -0.12033043 -0.48402981
 -0.46302898  0.26961063  2.42894744 -0.71442437  0.13375298  0.91104754
 -2.5858659   3.18889039  2.10553608  1.67571372  2.66327591] 3.1591256375798777 False {'reward_run': 3.3091713066587047, 'reward_ctrl': -0.1500456690788269}
[ 0.99296564 -0.25864738  0.6865458   0.48028353 -0.629379    0.20405395] [-0.49034305  3.177405    0.03441913 -0.35890413  0.22296464  0.08335358
 -0.40381896  0.20020911  0.33152502 -0.6865648   2.34898223 14.79477751
 -9.82859631  7.48955016 13.59472235 -0.95153372 -3.3168251 ] 0.8213017610342277 False {'reward_run': 1.0405669835836662, 'reward_ctrl': -0.21926522254943848}
[ 0.93991977  0.12303426 -0.38817883 -0.13431913  0.03917798  0.5128456 ] [-0.49415179  3.18910447  0.56855957 -0.21509497  0.03569081  0.31477839
  0.04273984  0.17520361  1.65651375  0.04086208 -0.42943723  7.96417941
  8.72428849 -7.2481864

[-0.07433974  0.09892424  0.93926936  0.22295074  0.05560067  0.8251597 ] [-0.52830564  3.42968858  0.26053343  0.43933892  0.46741602  0.25691339
 -0.04510853  0.05991323  2.17385712 -0.56727019  1.90978588 -6.82821597
 -3.80487704  4.50723027 -1.42801974 -1.82849963 11.84377682] 2.029849946508179 False {'reward_run': 2.1929726004693606, 'reward_ctrl': -0.16312265396118164}
[ 0.63507193 -0.6324187  -0.1037721   0.70220596 -0.03311871 -0.28356928] [ -0.49591503   3.43491687   0.38017657  -0.06666547   0.18124422
   0.44078637  -0.04399739   0.26051189   1.06554948   0.35076486
   0.59835939   2.90963748 -13.63859956  -9.18784272   3.60289727
   0.68119309  -0.90662965] 0.9349324086037953 False {'reward_run': 1.0737964012948353, 'reward_ctrl': -0.13886399269104005}
[ 0.78452516  0.39250866  0.47244662 -0.3296235   0.00769787 -0.96811205] [ -0.49799678   3.40042547   0.31447069  -0.14373142   0.05312712
   0.23186492   0.20242445  -0.12148862   2.18497466  -0.21594683
  -1.23673135  -3.1

KeyboardInterrupt: 

In [5]:
mc.close()

In [6]:
mc.best_action(env.get_state())

BrokenPipeError: [Errno 32] Broken pipe