In [1]:
from ilqr import iLQR
import gym
import numpy as np
import pandas as pd
import time

from aprl.agents import MujocoFiniteDiffDynamicsPerformance
from aprl.envs.mujoco_costs import get_cost
from experiments.common import set_seeds, make_env, fit_ilqr, \
                               on_iteration, receding, multi_evaluate

WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'


Logging to /tmp/openai-2019-02-02-10-10-00-610410
Choosing the latest nvidia driver: /usr/lib/nvidia-396, among ['/usr/lib/nvidia-375', '/usr/lib/nvidia-396']
Choosing the latest nvidia driver: /usr/lib/nvidia-396, among ['/usr/lib/nvidia-375', '/usr/lib/nvidia-396']


In [2]:
seed = 42
set_seeds(seed)

env_name = 'InvertedPendulum-v2'
env, us_init = make_env(env_name, seed=seed)
dynamics = {'performance': MujocoFiniteDiffDynamicsPerformance(env)}
x0s = {k: dyn.get_state() for k, dyn in dynamics.items()}

costs = {k: get_cost(env_name) for k in dynamics.keys()}
ilqrs = {k: iLQR(dyn, costs[k], len(us_init))  
         for k, dyn in dynamics.items()}

In [3]:
xs, us = fit_ilqr(ilqrs, x0s, us_init)

dict_keys(['performance'])
*** Fitting performance ***
iteration -1 converged 8000.546301728309 [-1.00891306e+00 -1.57327613e+00 -2.39078527e-01  3.66173836e-05] [1.0628469]
iteration 0 accepted 4163.297646900738 [ 9.86032424e-01 -1.57327643e+00 -7.09389833e-02 -4.13490150e-07] [-0.0660465]
iteration 1 accepted 4085.4790703680055 [ 9.99589959e-01 -1.57327637e+00 -2.24617126e-03 -1.29597510e-08] [-0.00208583]
iteration 2 accepted 4047.6417957739595 [ 9.99888747e-01 -1.57327637e+00 -1.70797153e-05 -1.16005145e-10] [-1.7101862e-05]
iteration 3 accepted 3511.784776912087 [ 9.96944675e-01 -1.57327637e+00 -1.16681165e-03 -3.57811689e-10] [-1.1345905e-05]
iteration 4 accepted 3129.1146728283534 [ 9.99885290e-01 -1.57327637e+00  1.35484353e-06 -1.20823857e-11] [-2.688765e-07]
iteration 5 accepted 3109.4496996000526 [ 9.99920827e-01 -1.57327637e+00  1.41322777e-06 -1.17482269e-11] [-1.9737696e-07]
iteration 6 accepted 3056.062515262745 [ 9.99936986e-01 -1.57327637e+00  1.41047656e-06 -1.1782571

# Receding horizon

In [5]:
for k, ilqr in ilqrs.items():
    underlying = 'receding_' + k
    dynamics[underlying] = dynamics[k]
    x0s[underlying] = x0s[k]
    xs[underlying], us[underlying] = receding(env, ilqr, x0s[k], us_init)

iteration 0 r = 1.0, x = [[-0.00251713 -0.00031323  0.00841542 -0.00036109]
 [-0.0033249   0.00199222 -0.08901676  0.22941983]], u = [[-0.5292973]]
iteration 1 r = 1.0, x = [[-0.0033249   0.00199222 -0.08901676  0.22941983]
 [-0.00561983  0.00774675 -0.14043524  0.34575193]], u = [[-0.28389445]]
iteration 2 r = 1.0, x = [[-0.00561983  0.00774675 -0.14043524  0.34575193]
 [-0.0086619   0.01515624 -0.16380512  0.39558472]], u = [[-0.13228847]]
iteration 3 r = 1.0, x = [[-0.0086619   0.01515624 -0.16380512  0.39558472]
 [-0.01199674  0.02316965 -0.16975357  0.40650024]], u = [[-0.03629446]]
iteration 4 r = 1.0, x = [[-0.01199674  0.02316965 -0.16975357  0.40650024]
 [-0.01533513  0.03116269 -0.164181    0.39372604]], u = [[0.02878692]]
iteration 5 r = 1.0, x = [[-0.01533513  0.03116269 -0.164181    0.39372604]
 [-0.01826437  0.03823806 -0.12888825  0.31514031]], u = [[0.19349981]]
iteration 6 r = 1.0, x = [[-0.01826437  0.03823806 -0.12888825  0.31514031]
 [-0.02056362  0.04397665 -0.1011

iteration 55 r = 1.0, x = [[ 0.13349496 -0.03650474 -0.00881304  0.06061798]
 [ 0.1332397  -0.03528492 -0.01672337  0.06147852]], u = [[-0.05613283]]
iteration 56 r = 1.0, x = [[ 0.1332397  -0.03528492 -0.01672337  0.06147852]
 [ 0.13282981 -0.03405095 -0.02427542  0.06203663]], u = [[-0.05386677]]
iteration 57 r = 1.0, x = [[ 0.13282981 -0.03405095 -0.02427542  0.06203663]
 [ 0.13227242 -0.03280859 -0.03147485  0.0623204 ]], u = [[-0.05161717]]
iteration 58 r = 1.0, x = [[ 0.13227242 -0.03280859 -0.03147485  0.0623204 ]
 [ 0.1315745  -0.03156307 -0.038328    0.06235602]], u = [[-0.04939021]]
iteration 59 r = 1.0, x = [[ 0.1315745  -0.03156307 -0.038328    0.06235602]
 [ 0.13074292 -0.03031908 -0.04484177  0.06216791]], u = [[-0.04719136]]
iteration 60 r = 1.0, x = [[ 0.13074292 -0.03031908 -0.04484177  0.06216791]
 [ 0.12978438 -0.02908088 -0.05102357  0.06177884]], u = [[-0.04502549]]
iteration 61 r = 1.0, x = [[ 0.12978438 -0.02908088 -0.05102357  0.06177884]
 [ 0.12870545 -0.027852

iteration 110 r = 1.0, x = [[ 0.02102157  0.00137681 -0.11897677  0.00607517]
 [ 0.01864961  0.00149277 -0.11822134  0.00553652]], u = [[0.00382741]]
iteration 111 r = 1.0, x = [[ 0.01864961  0.00149277 -0.11822134  0.00553652]
 [ 0.01629293  0.00159823 -0.11744843  0.00502502]], u = [[0.00398013]]
iteration 112 r = 1.0, x = [[ 0.01629293  0.00159823 -0.11744843  0.00502502]
 [ 0.01395186  0.00169374 -0.11666001  0.0045397 ]], u = [[0.00411825]]
iteration 113 r = 1.0, x = [[ 0.01395186  0.00169374 -0.11666001  0.0045397 ]
 [ 0.0116267   0.00177981 -0.11585821  0.00408027]], u = [[0.00424103]]
iteration 114 r = 1.0, x = [[ 0.0116267   0.00177981 -0.11585821  0.00408027]
 [ 0.00931768  0.00185695 -0.11504465  0.0036455 ]], u = [[0.00435137]]
iteration 115 r = 1.0, x = [[ 0.00931768  0.00185695 -0.11504465  0.0036455 ]
 [ 0.00702504  0.00192564 -0.11422104  0.00323458]], u = [[0.00444905]]
iteration 116 r = 1.0, x = [[ 0.00702504  0.00192564 -0.11422104  0.00323458]
 [ 0.00474895  0.00198

iteration 165 r = 1.0, x = [[-0.08573105  0.00110366 -0.07772642 -0.00176619]
 [-0.08728003  0.00106857 -0.07717083 -0.00174617]], u = [[0.00321831]]
iteration 166 r = 1.0, x = [[-0.08728003  0.00106857 -0.07717083 -0.00174617]
 [-0.08881796  0.00103389 -0.07662267 -0.00172539]], u = [[0.00317112]]
iteration 167 r = 1.0, x = [[-0.08881796  0.00103389 -0.07662267 -0.00172539]
 [-0.09034501  0.00099963 -0.07608186 -0.00170392]], u = [[0.00312451]]
iteration 168 r = 1.0, x = [[-0.09034501  0.00099963 -0.07608186 -0.00170392]
 [-0.09186131  0.0009658  -0.07554824 -0.00168192]], u = [[0.00307875]]
iteration 169 r = 1.0, x = [[-0.09186131  0.0009658  -0.07554824 -0.00168192]
 [-0.09336702  0.00093242 -0.07502173 -0.00165943]], u = [[0.00303356]]
iteration 170 r = 1.0, x = [[-0.09336702  0.00093242 -0.07502173 -0.00165943]
 [-0.09486226  0.00089949 -0.0745022  -0.00163653]], u = [[0.00298906]]
iteration 171 r = 1.0, x = [[-0.09486226  0.00089949 -0.0745022  -0.00163653]
 [-0.09634718  0.00086

iteration 217 r = 1.0, x = [[-1.54329515e-01 -8.63222167e-05 -5.63117520e-02 -6.19088433e-04]
 [-1.55452579e-01 -9.86904065e-05 -5.59946100e-02 -6.18778905e-04]], u = [[0.00170946]]
iteration 218 r = 1.0, x = [[-1.55452579e-01 -9.86904065e-05 -5.59946100e-02 -6.18778905e-04]
 [-1.56569374e-01 -1.10934371e-04 -5.56848842e-02 -6.06742811e-04]], u = [[0.0016681]]
iteration 219 r = 1.0, x = [[-1.56569374e-01 -1.10934371e-04 -5.56848842e-02 -6.06742811e-04]
 [-1.57679945e-01 -1.23068365e-04 -5.53721869e-02 -6.07675109e-04]], u = [[0.00168297]]
iteration 220 r = 1.0, x = [[-1.57679945e-01 -1.23068365e-04 -5.53721869e-02 -6.07675109e-04]
 [-1.58784337e-01 -1.35100804e-04 -5.50669359e-02 -5.96668066e-04]], u = [[0.00164151]]
iteration 221 r = 1.0, x = [[-1.58784337e-01 -1.35100804e-04 -5.50669359e-02 -5.96668066e-04]
 [-1.59882595e-01 -1.47039472e-04 -5.47588440e-02 -5.98196138e-04]], u = [[0.00165571]]
iteration 222 r = 1.0, x = [[-1.59882595e-01 -1.47039472e-04 -5.47588440e-02 -5.98196138e-0

iteration 270 r = 1.0, x = [[-0.20575803  0.00353992 -0.02677921 -0.00477664]
 [-0.20628129  0.00344081 -0.02554681 -0.00514172]], u = [[0.00829435]]
iteration 271 r = 1.0, x = [[-0.20628129  0.00344081 -0.02554681 -0.00514172]
 [-0.20678028  0.00333492 -0.02435157 -0.00545515]], u = [[0.00807838]]
iteration 272 r = 1.0, x = [[-0.20678028  0.00333492 -0.02435157 -0.00545515]
 [-0.20725574  0.00322324 -0.02319372 -0.00572091]], u = [[0.0078574]]
iteration 273 r = 1.0, x = [[-0.20725574  0.00322324 -0.02319372 -0.00572091]
 [-0.20770842  0.0031067  -0.02207337 -0.00594275]], u = [[0.00763259]]
iteration 274 r = 1.0, x = [[-0.20770842  0.0031067  -0.02207337 -0.00594275]
 [-0.20813906  0.00298614 -0.02099047 -0.00612419]], u = [[0.00740506]]
iteration 275 r = 1.0, x = [[-0.20813906  0.00298614 -0.02099047 -0.00612419]
 [-0.20854843  0.00286232 -0.01994489 -0.00626855]], u = [[0.00717578]]
iteration 276 r = 1.0, x = [[-0.20854843  0.00286232 -0.01994489 -0.00626855]
 [-0.20893725  0.002735

iteration 324 r = 1.0, x = [[-0.21465764 -0.00126264 -0.00033327 -0.00147175]
 [-0.21466369 -0.00129124 -0.00027071 -0.00139215]], u = [[0.00050337]]
iteration 325 r = 1.0, x = [[-2.14663687e-01 -1.29124137e-03 -2.70705856e-04 -1.39214641e-03]
 [-2.14668530e-01 -1.31828744e-03 -2.13313514e-04 -1.31576596e-03]], u = [[0.0004646]]
iteration 326 r = 1.0, x = [[-2.14668530e-01 -1.31828744e-03 -2.13313514e-04 -1.31576596e-03]
 [-2.14672274e-01 -1.34383922e-03 -1.60774031e-04 -1.24254405e-03]], u = [[0.00042808]]
iteration 327 r = 1.0, x = [[-2.14672274e-01 -1.34383922e-03 -1.60774031e-04 -1.24254405e-03]
 [-2.14675012e-01 -1.36795912e-03 -1.12787394e-04 -1.17241025e-03]], u = [[0.00039372]]
iteration 328 r = 1.0, x = [[-2.14675012e-01 -1.36795912e-03 -1.12787394e-04 -1.17241025e-03]
 [-2.14676834e-01 -1.39070809e-03 -6.90679849e-05 -1.10529099e-03]], u = [[0.00036141]]
iteration 329 r = 1.0, x = [[-2.14676834e-01 -1.39070809e-03 -6.90679849e-05 -1.10529099e-03]
 [-2.14677821e-01 -1.41214559

iteration 371 r = 1.0, x = [[-2.14526327e-01 -1.68585889e-03  1.46079629e-04 -1.22793871e-05]
 [-2.14523460e-01 -1.68606116e-03  1.40638751e-04 -8.00363363e-06]], u = [[-3.43838545e-05]]
iteration 372 r = 1.0, x = [[-2.14523460e-01 -1.68606116e-03  1.40638751e-04 -8.00363363e-06]
 [-2.14520701e-01 -1.68618190e-03  1.35272863e-04 -4.11467553e-06]], u = [[-3.41849796e-05]]
iteration 373 r = 1.0, x = [[-2.14520701e-01 -1.68618190e-03  1.35272863e-04 -4.11467553e-06]
 [-2.14518048e-01 -1.68622858e-03  1.29991872e-04 -5.87596451e-07]], u = [[-3.38960763e-05]]
iteration 374 r = 1.0, x = [[-2.14518048e-01 -1.68622858e-03  1.29991872e-04 -5.87596451e-07]
 [-2.14515500e-01 -1.68620820e-03  1.24804491e-04  2.60119062e-06]], u = [[-3.35265622e-05]]
iteration 375 r = 1.0, x = [[-2.14515500e-01 -1.68620820e-03  1.24804491e-04  2.60119062e-06]
 [-2.14513055e-01 -1.68612729e-03  1.19718275e-04  5.47413033e-06]], u = [[-3.3085507e-05]]
iteration 376 r = 1.0, x = [[-2.14513055e-01 -1.68612729e-03  1.19

iteration 415 r = 1.0, x = [[-2.14472349e-01 -1.67173373e-03  1.20861819e-05  1.34745584e-05]
 [-2.14472117e-01 -1.67146964e-03  1.11515056e-05  1.29649328e-05]], u = [[-6.95038027e-06]]
iteration 416 r = 1.0, x = [[-2.14472117e-01 -1.67146964e-03  1.11515056e-05  1.29649328e-05]
 [-2.14471903e-01 -1.67121566e-03  1.02713096e-05  1.24629954e-05]], u = [[-6.56372663e-06]]
iteration 417 r = 1.0, x = [[-2.14471903e-01 -1.67121566e-03  1.02713096e-05  1.24629954e-05]
 [-2.14471706e-01 -1.67097161e-03  9.44315444e-06  1.19696101e-05]], u = [[-6.19337236e-06]]
iteration 418 r = 1.0, x = [[-2.14471706e-01 -1.67097161e-03  9.44315444e-06  1.19696101e-05]
 [-2.14471524e-01 -1.67073733e-03  8.66466952e-06  1.14855299e-05]], u = [[-5.83892987e-06]]
iteration 419 r = 1.0, x = [[-2.14471524e-01 -1.67073733e-03  8.66466952e-06  1.14855299e-05]
 [-2.14471358e-01 -1.67051262e-03  7.93355413e-06  1.10114054e-05]], u = [[-5.49999805e-06]]
iteration 420 r = 1.0, x = [[-2.14471358e-01 -1.67051262e-03  7.9

iteration 459 r = 1.0, x = [[-2.14470252e-01 -1.66679870e-03 -8.38731764e-07  1.08541865e-06]
 [-2.14470269e-01 -1.66677787e-03 -8.41427837e-07  1.00039742e-06]], u = [[-9.013539e-08]]
iteration 460 r = 1.0, x = [[-2.14470269e-01 -1.66677787e-03 -8.41427837e-07  1.00039742e-06]
 [-2.14470286e-01 -1.66675869e-03 -8.41173095e-07  9.20376609e-07]], u = [[-6.53477504e-08]]
iteration 461 r = 1.0, x = [[-2.14470286e-01 -1.66675869e-03 -8.41173095e-07  9.20376609e-07]
 [-2.14470303e-01 -1.66674106e-03 -8.38252925e-07  8.45129859e-07]], u = [[-4.27416582e-08]]
iteration 462 r = 1.0, x = [[-2.14470303e-01 -1.66674106e-03 -8.38252925e-07  8.45129859e-07]
 [-2.14470320e-01 -1.66672488e-03 -8.32933723e-07  7.74437375e-07]], u = [[-2.21790376e-08]]
iteration 463 r = 1.0, x = [[-2.14470320e-01 -1.66672488e-03 -8.32933723e-07  7.74437375e-07]
 [-2.14470336e-01 -1.66671008e-03 -8.25463867e-07  7.08086006e-07]], u = [[-3.52858824e-09]]
iteration 464 r = 1.0, x = [[-2.14470336e-01 -1.66671008e-03 -8.254

iteration 504 r = 1.0, x = [[-2.14470732e-01 -1.66661759e-03 -1.87582836e-07 -7.95021150e-08]
 [-2.14470736e-01 -1.66661918e-03 -1.77410620e-07 -7.93161637e-08]], u = [[7.11454331e-08]]
iteration 505 r = 1.0, x = [[-2.14470736e-01 -1.66661918e-03 -1.77410620e-07 -7.93161637e-08]
 [-2.14470739e-01 -1.66662076e-03 -1.67652083e-07 -7.88945038e-08]], u = [[6.84561843e-08]]
iteration 506 r = 1.0, x = [[-2.14470739e-01 -1.66662076e-03 -1.67652083e-07 -7.88945038e-08]
 [-2.14470743e-01 -1.66662233e-03 -1.58298539e-07 -7.82612127e-08]], u = [[6.58073674e-08]]
iteration 507 r = 1.0, x = [[-2.14470743e-01 -1.66662233e-03 -1.58298539e-07 -7.82612127e-08]
 [-2.14470746e-01 -1.66662389e-03 -1.49340842e-07 -7.74387250e-08]], u = [[6.32035591e-08]]
iteration 508 r = 1.0, x = [[-2.14470746e-01 -1.66662389e-03 -1.49340842e-07 -7.74387250e-08]
 [-2.14470749e-01 -1.66662542e-03 -1.40769462e-07 -7.64479143e-08]], u = [[6.064874e-08]]
iteration 509 r = 1.0, x = [[-2.14470749e-01 -1.66662542e-03 -1.40769462

iteration 549 r = 1.0, x = [[-2.14470786e-01 -1.66666083e-03 -2.72163919e-09 -1.61732216e-08]
 [-2.14470786e-01 -1.66666114e-03 -2.07184003e-09 -1.52756058e-08]], u = [[5.28775806e-09]]
iteration 550 r = 1.0, x = [[-2.14470786e-01 -1.66666114e-03 -2.07184003e-09 -1.52756058e-08]
 [-2.14470786e-01 -1.66666144e-03 -1.47808369e-09 -1.44157057e-08]], u = [[4.86501032e-09]]
iteration 551 r = 1.0, x = [[-2.14470786e-01 -1.66666144e-03 -1.47808369e-09 -1.44157057e-08]
 [-2.14470786e-01 -1.66666172e-03 -9.36863213e-10 -1.35926362e-08]], u = [[4.46748006e-09]]
iteration 552 r = 1.0, x = [[-2.14470786e-01 -1.66666172e-03 -9.36863213e-10 -1.35926362e-08]
 [-2.14470786e-01 -1.66666198e-03 -4.44842471e-10 -1.28054778e-08]], u = [[4.09400301e-09]]
iteration 553 r = 1.0, x = [[-2.14470786e-01 -1.66666198e-03 -4.44842471e-10 -1.28054778e-08]
 [-2.14470786e-01 -1.66666223e-03  1.14894159e-12 -1.20532821e-08]], u = [[3.74344671e-09]]
iteration 554 r = 1.0, x = [[-2.14470786e-01 -1.66666223e-03  1.148941

iteration 593 r = 1.0, x = [[-2.14470784e-01 -1.66666535e-03  1.85607030e-09 -2.17736788e-10]
 [-2.14470784e-01 -1.66666536e-03  1.78900143e-09 -1.59728988e-10]], u = [[-4.1939823e-10]]
iteration 594 r = 1.0, x = [[-2.14470784e-01 -1.66666536e-03  1.78900143e-09 -1.59728988e-10]
 [-2.14470784e-01 -1.66666536e-03  1.72268210e-09 -1.06810411e-10]], u = [[-4.18435383e-10]]
iteration 595 r = 1.0, x = [[-2.14470784e-01 -1.66666536e-03  1.72268210e-09 -1.06810411e-10]
 [-2.14470784e-01 -1.66666536e-03  1.65725243e-09 -5.86600413e-11]], u = [[-4.16225388e-10]]
iteration 596 r = 1.0, x = [[-2.14470784e-01 -1.66666536e-03  1.65725243e-09 -5.86600413e-11]
 [-2.14470784e-01 -1.66666536e-03  1.59282866e-09 -1.49550022e-11]], u = [[-4.12936434e-10]]
iteration 597 r = 1.0, x = [[-2.14470784e-01 -1.66666536e-03  1.59282866e-09 -1.49550022e-11]
 [-2.14470784e-01 -1.66666536e-03  1.52952447e-09  2.45823966e-11]], u = [[-4.08619102e-10]]
iteration 598 r = 1.0, x = [[-2.14470784e-01 -1.66666536e-03  1.52

iteration 637 r = 1.0, x = [[-2.14470784e-01 -1.66666519e-03  1.61397190e-10  1.71332448e-10]
 [-2.14470784e-01 -1.66666519e-03  1.49203395e-10  1.65039665e-10]], u = [[-9.03762589e-11]]
iteration 638 r = 1.0, x = [[-2.14470784e-01 -1.66666519e-03  1.49203395e-10  1.65039665e-10]
 [-2.14470784e-01 -1.66666518e-03  1.37709676e-10  1.58823110e-10]], u = [[-8.54261251e-11]]
iteration 639 r = 1.0, x = [[-2.14470784e-01 -1.66666518e-03  1.37709676e-10  1.58823110e-10]
 [-2.14470784e-01 -1.66666518e-03  1.26881317e-10  1.52704680e-10]], u = [[-8.07016539e-11]]
iteration 640 r = 1.0, x = [[-2.14470784e-01 -1.66666518e-03  1.26881317e-10  1.52704680e-10]
 [-2.14470784e-01 -1.66666518e-03  1.16693777e-10  1.46682547e-10]], u = [[-7.61477138e-11]]
iteration 641 r = 1.0, x = [[-2.14470784e-01 -1.66666518e-03  1.16693777e-10  1.46682547e-10]
 [-2.14470784e-01 -1.66666517e-03  1.07114396e-10  1.40774918e-10]], u = [[-7.18079994e-11]]
iteration 642 r = 1.0, x = [[-2.14470784e-01 -1.66666517e-03  1.0

iteration 681 r = 1.0, x = [[-2.14470784e-01 -1.66666513e-03 -1.01094938e-11  1.45149119e-11]
 [-2.14470784e-01 -1.66666513e-03 -1.01912159e-11  1.34082497e-11]], u = [[-1.49925435e-12]]
iteration 682 r = 1.0, x = [[-2.14470784e-01 -1.66666513e-03 -1.01912159e-11  1.34082497e-11]
 [-2.14470784e-01 -1.66666512e-03 -1.02301605e-11  1.23599682e-11]], u = [[-1.15069892e-12]]
iteration 683 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -1.02301605e-11  1.23599682e-11]
 [-2.14470784e-01 -1.66666512e-03 -1.02331770e-11  1.13746389e-11]], u = [[-8.47435381e-13]]
iteration 684 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -1.02331770e-11  1.13746389e-11]
 [-2.14470784e-01 -1.66666512e-03 -1.02033792e-11  1.04484976e-11]], u = [[-5.68887376e-13]]
iteration 685 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -1.02033792e-11  1.04484976e-11]
 [-2.14470784e-01 -1.66666512e-03 -1.01432377e-11  9.57692277e-12]], u = [[-3.11106852e-13]]
iteration 686 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -1.0

iteration 726 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -2.43494207e-12 -9.65469990e-13]
 [-2.14470784e-01 -1.66666512e-03 -2.30475296e-12 -9.67928264e-13]], u = [[9.06660481e-13]]
iteration 727 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -2.30475296e-12 -9.67928264e-13]
 [-2.14470784e-01 -1.66666512e-03 -2.17856433e-12 -9.69815712e-13]], u = [[8.79717839e-13]]
iteration 728 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -2.17856433e-12 -9.69815712e-13]
 [-2.14470784e-01 -1.66666512e-03 -2.05894386e-12 -9.65135076e-13]], u = [[8.38741249e-13]]
iteration 729 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -2.05894386e-12 -9.65135076e-13]
 [-2.14470784e-01 -1.66666512e-03 -1.94709028e-12 -9.51245876e-13]], u = [[7.9104887e-13]]
iteration 730 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -1.94709028e-12 -9.51245876e-13]
 [-2.14470784e-01 -1.66666512e-03 -1.83836318e-12 -9.39204019e-13]], u = [[7.68409489e-13]]
iteration 731 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -1.8383631

iteration 771 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -4.30288679e-14 -2.11098201e-13]
 [-2.14470784e-01 -1.66666512e-03 -3.41866511e-14 -1.99862543e-13]], u = [[7.11751387e-14]]
iteration 772 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -3.41866511e-14 -1.99862543e-13]
 [-2.14470784e-01 -1.66666512e-03 -2.59557484e-14 -1.89404417e-13]], u = [[6.63125119e-14]]
iteration 773 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -2.59557484e-14 -1.89404417e-13]
 [-2.14470784e-01 -1.66666512e-03 -1.87920687e-14 -1.78500535e-13]], u = [[5.90754126e-14]]
iteration 774 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -1.87920687e-14 -1.78500535e-13]
 [-2.14470784e-01 -1.66666512e-03 -1.39052042e-14 -1.64246813e-13]], u = [[4.529329e-14]]
iteration 775 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -1.39052042e-14 -1.64246813e-13]
 [-2.14470784e-01 -1.66666512e-03 -8.42116115e-15 -1.53356951e-13]], u = [[4.71509029e-14]]
iteration 776 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -8.42116115

iteration 815 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  1.99300231e-14 -1.37892541e-16]
 [-2.14470784e-01 -1.66666512e-03  1.88937130e-14  1.10646913e-15]], u = [[-6.31220841e-15]]
iteration 816 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  1.88937130e-14  1.10646913e-15]
 [-2.14470784e-01 -1.66666512e-03  1.69693569e-14  4.41779164e-15]], u = [[-1.11677102e-14]]
iteration 817 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  1.69693569e-14  4.41779164e-15]
 [-2.14470784e-01 -1.66666512e-03  1.74138894e-14  2.08906874e-15]], u = [[1.64481646e-15]]
iteration 818 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  1.74138894e-14  2.08906874e-15]
 [-2.14470784e-01 -1.66666512e-03  1.73628683e-14  1.03382947e-15]], u = [[-9.66299535e-16]]
iteration 819 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  1.73628683e-14  1.03382947e-15]
 [-2.14470784e-01 -1.66666512e-03  1.68701133e-14  1.04960570e-15]], u = [[-3.34541853e-15]]
iteration 820 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  1.68

iteration 859 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  2.29038753e-15  3.49297763e-15]
 [-2.14470784e-01 -1.66666512e-03  8.06358287e-16  6.39022240e-15]], u = [[-8.48282392e-15]]
iteration 860 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  8.06358287e-16  6.39022240e-15]
 [-2.14470784e-01 -1.66666512e-03  1.31505301e-15  4.56542692e-15]], u = [[2.31295659e-15]]
iteration 861 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  1.31505301e-15  4.56542692e-15]
 [-2.14470784e-01 -1.66666512e-03  2.30285154e-15  1.71628214e-15]], u = [[4.99866782e-15]]
iteration 862 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  2.30285154e-15  1.71628214e-15]
 [-2.14470784e-01 -1.66666512e-03  1.74349938e-15  2.61269784e-15]], u = [[-3.32652946e-15]]
iteration 863 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  1.74349938e-15  2.61269784e-15]
 [-2.14470784e-01 -1.66666512e-03  1.16710100e-15  3.54163817e-15]], u = [[-3.43038234e-15]]
iteration 864 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  1.167

iteration 903 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -9.02988116e-17  1.92120197e-15]
 [-2.14470784e-01 -1.66666512e-03 -1.21261470e-15  4.41717363e-15]], u = [[-6.20958075e-15]]
iteration 904 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -1.21261470e-15  4.41717363e-15]
 [-2.14470784e-01 -1.66666512e-03 -2.19047205e-16  1.90022044e-15]], u = [[5.25865646e-15]]
iteration 905 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -2.19047205e-16  1.90022044e-15]
 [-2.14470784e-01 -1.66666512e-03 -1.27365249e-15  4.30890532e-15]], u = [[-5.78981125e-15]]
iteration 906 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -1.27365249e-15  4.30890532e-15]
 [-2.14470784e-01 -1.66666512e-03  1.01175162e-15 -1.19542569e-15]], u = [[1.23205169e-14]]
iteration 907 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  1.01175162e-15 -1.19542569e-15]
 [-2.14470784e-01 -1.66666512e-03 -7.00949570e-16  2.87179040e-15]], u = [[-9.27494752e-15]]
iteration 908 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -7.009

iteration 947 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  9.82416963e-16  1.42852617e-15]
 [-2.14470784e-01 -1.66666512e-03  1.54451110e-15  1.48195621e-16]], u = [[3.09712256e-15]]
iteration 948 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  1.54451110e-15  1.48195621e-16]
 [-2.14470784e-01 -1.66666512e-03 -2.92018764e-16  4.56267013e-15]], u = [[-9.90186922e-15]]
iteration 949 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -2.92018764e-16  4.56267013e-15]
 [-2.14470784e-01 -1.66666512e-03  3.99827631e-16  2.92731633e-15]], u = [[3.75337348e-15]]
iteration 950 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  3.99827631e-16  2.92731633e-15]
 [-2.14470784e-01 -1.66666512e-03  2.18846883e-15 -1.19584662e-15]], u = [[9.79210276e-15]]
iteration 951 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  2.18846883e-15 -1.19584662e-15]
 [-2.14470784e-01 -1.66666512e-03  2.29796744e-15 -1.24422935e-15]], u = [[7.70923844e-16]]
iteration 952 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  2.29796

iteration 991 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  8.86012151e-16 -9.45063793e-16]
 [-2.14470784e-01 -1.66666512e-03  7.32508666e-16 -7.24887174e-16]], u = [[-9.29328496e-16]]
iteration 992 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  7.32508666e-16 -7.24887174e-16]
 [-2.14470784e-01 -1.66666512e-03  1.03305053e-15 -1.57793156e-15]], u = [[1.5343378e-15]]
iteration 993 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  1.03305053e-15 -1.57793156e-15]
 [-2.14470784e-01 -1.66666512e-03  8.43840045e-16 -1.26092856e-15]], u = [[-1.11260661e-15]]
iteration 994 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  8.43840045e-16 -1.26092856e-15]
 [-2.14470784e-01 -1.66666512e-03  6.24298408e-16 -9.18206352e-16]], u = [[-1.31293328e-15]]
iteration 995 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03  6.24298408e-16 -9.18206352e-16]
 [-2.14470784e-01 -1.66666512e-03 -1.04165065e-15  2.80998095e-15]], u = [[-9.19279472e-15]]
iteration 996 r = 1.0, x = [[-2.14470784e-01 -1.66666512e-03 -1.041

# Rollouts

In [8]:
multi_evaluate(env, dynamics, x0s, us)

performance
receding_performance


rewards  lengths
performance              90.0       90
receding_performance    232.0      232