In [ ]:
from ilqr import iLQR
import gym
import numpy as np
import pandas as pd
import time

from aprl.agents import MujocoFiniteDiffDynamicsPerformance
from aprl.envs.mujoco_costs import get_cost
from experiments.common import set_seeds, make_env, fit_ilqr, \
                               on_iteration, receding, multi_evaluate

In [4]:
seed = 42
set_seeds(seed)

env_name = 'InvertedDoublePendulum-v2'
env, us_init = make_env(env_name, seed=seed, horizon=100)
dynamics = {'performance': MujocoFiniteDiffDynamicsPerformance(env)}
x0s = {k: dyn.get_state() for k, dyn in dynamics.items()}

costs = {k: get_cost(env_name) for k in dynamics.keys()}
ilqrs = {k: iLQR(dyn, costs[k], len(us_init))  
         for k, dyn in dynamics.items()}

In [5]:
xs, us = fit_ilqr(ilqrs, x0s, us_init)

dict_keys(['performance'])
*** Fitting performance ***
iteration -1 converged 1072.8584477859247 [-0.64029087  3.3499411   0.25855345  0.65627266  7.18869424  2.83578306] [-0.7842171]
iteration 0 failed 1072.8584477859247 [-0.64029087  3.3499411   0.25855345  0.65627266  7.18869424  2.83578306] [-0.7842171]
iteration 1 failed 1072.8584477859247 [-0.64029087  3.3499411   0.25855345  0.65627266  7.18869424  2.83578306] [-0.7842171]
iteration 2 accepted 1059.941243851374 [-0.66334038  3.32649992  0.27856225  0.57285335  6.84846271  3.8956121 ] [-0.7839354]
iteration 3 failed 1059.941243851374 [-0.66334038  3.32649992  0.27856225  0.57285335  6.84846271  3.8956121 ] [-0.7839354]
iteration 4 accepted 915.3045732401388 [-0.59995386  3.0761087   0.20781475  0.04160346  3.4572538  11.10813061] [-0.73891616]
iteration 5 failed 915.3045732401388 [-0.59995386  3.0761087   0.20781475  0.04160346  3.4572538  11.10813061] [-0.73891616]
iteration 6 accepted 357.29716793786497 [ 0.05763148  2.88049626

# Receding horizon

In [9]:
for k, ilqr in ilqrs.items():
    underlying = 'receding_' + k
    dynamics[underlying] = dynamics[k]
    x0s[underlying] = x0s[k]
    xs[underlying], us[underlying] = receding(env, ilqr, x0s[k], us_init, horizon=2000, step_size=5)

iteration 0 x = [[-2.51713244e-02 -3.13228967e-03  8.41541642e-02  2.78393152e-01
  -8.96038897e-02 -8.23645605e-02]
 [-2.30546428e-02 -2.73084678e-03  8.18630811e-02  1.44947338e-01
   1.69889282e-01 -3.75888164e-01]
 [-2.20716243e-02 -1.47207303e-04  7.71597407e-02  5.16305864e-02
   3.47088796e-01 -5.65405536e-01]
 [-2.18733970e-02  3.90881604e-03  7.09333390e-02 -1.20300173e-02
   4.64519595e-01 -6.80839525e-01]
 [-2.22015715e-02  8.92125159e-03  6.38169963e-02 -5.36618124e-02
   5.38462678e-01 -7.43584246e-01]
 [-2.28637554e-02  1.45145173e-02  5.62601789e-02 -7.88392976e-02
   5.80737757e-01 -7.69035389e-01]], u = [[-0.28724512]
 [-0.20120426]
 [-0.13727081]
 [-0.08946668]
 [-0.05347044]]
iteration 5 x = [[-0.02286376  0.01451452  0.05626018 -0.0788393   0.58073776 -0.76903539]
 [-0.02374376  0.02047286  0.04850594 -0.09722919  0.61150513 -0.78311848]
 [-0.02474382  0.02661982  0.04074632 -0.10285549  0.61848128 -0.77013834]
 [-0.02575514  0.03275667  0.03320183 -0.09948176  0.60

iteration 80 x = [[ 0.36537107 -0.07867554  0.0846208   0.54366648  0.04739417 -0.13348775]
 [ 0.3704281  -0.07758204  0.08269588  0.46772806  0.17140011 -0.25172215]
 [ 0.37473421 -0.07526281  0.07960241  0.39346679  0.29266331 -0.36746151]
 [ 0.37831124 -0.07175305  0.07537199  0.3218953   0.40962317 -0.47936359]
 [ 0.38119218 -0.06710585  0.07005279  0.25423315  0.52025852 -0.58544566]
 [ 0.38342432 -0.0613991   0.06371902  0.19212376  0.62162742 -0.68247949]], u = [[-0.17499133]
 [-0.17113008]
 [-0.16488104]
 [-0.15581784]
 [-0.14305549]]
iteration 85 x = [[ 0.38342432 -0.0613991   0.06371902  0.19212376  0.62162742 -0.68247949]
 [ 0.38507664 -0.05475125  0.05649177  0.1382606   0.70856048 -0.76430584]
 [ 0.38626098 -0.04736561  0.04859664  0.09851905  0.76923829 -0.81616589]
 [ 0.3872358  -0.03974579  0.0406399   0.09635921  0.75540538 -0.77663784]
 [ 0.38694812 -0.02968644  0.02977036 -0.15402859  1.25738616 -1.399226  ]
 [ 0.38507074 -0.01647507  0.01503563 -0.22159282  1.386035

iteration 160 x = [[ 9.90415299e-01 -5.96876235e-01  9.04216109e-02  6.48747151e-03
  -1.74211235e+00  1.54072215e+00]
 [ 9.90455025e-01 -6.14871826e-01  1.06677821e-01  1.93082383e-03
  -1.85842685e+00  1.71262516e+00]
 [ 9.90449507e-01 -6.34051152e-01  1.24691141e-01 -2.32129987e-03
  -1.97920765e+00  1.89242691e+00]
 [ 9.90405654e-01 -6.54464512e-01  1.44544174e-01 -5.69287339e-03
  -2.10523921e+00  2.08040934e+00]
 [ 9.90340659e-01 -6.76175507e-01  1.66325433e-01 -6.84504494e-03
  -2.23820742e+00  2.27730357e+00]
 [ 9.88502641e-01 -6.96780008e-01  1.87865359e-01 -3.59779838e-01
  -1.88863957e+00  2.04384709e+00]], u = [[ 0.20229663]
 [ 0.11043357]
 [ 0.0173227 ]
 [-0.01222115]
 [-1.10608256]]
iteration 165 x = [[ 0.98850264 -0.69678001  0.18786536 -0.35977984 -1.88863957  2.04384709]
 [ 0.98508887 -0.71663638  0.20962113 -0.32328202 -2.08221625  2.30619063]
 [ 0.98303474 -0.7396986   0.23493795 -0.08858849 -2.52609559  2.74734778]
 [ 0.98187808 -0.76535808  0.26323965 -0.14284165 -

iteration 230 x = [[ 2.73183899e-02 -4.13950309e+00 -1.25421616e+00 -1.97913096e+00
  -7.98246547e+00  2.44503639e+00]
 [ 6.18061755e-03 -4.22126417e+00 -1.21949410e+00 -2.24551861e+00
  -8.35457813e+00  4.48969648e+00]
 [-1.39812138e-02 -4.30238413e+00 -1.17662856e+00 -1.78950280e+00
  -7.87763798e+00  4.06989805e+00]
 [-2.96597712e-02 -4.37897825e+00 -1.13832358e+00 -1.34858014e+00
  -7.44912271e+00  3.58170254e+00]
 [-4.26291262e-02 -4.45302987e+00 -1.09976177e+00 -1.24566530e+00
  -7.36046842e+00  4.12225170e+00]
 [-5.62754840e-02 -4.52759671e+00 -1.05053121e+00 -1.48228128e+00
  -7.54591022e+00  5.71491182e+00]], u = [[-7.76929808]
 [ 1.54389251]
 [ 1.04128707]
 [ 0.04881958]
 [-0.95410737]]
iteration 235 x = [[-0.05627548 -4.52759671 -1.05053121 -1.48228128 -7.54591022  5.71491182]
 [-0.07232456 -4.6039001  -0.98537643 -1.72608686 -7.71089242  7.30926702]
 [-0.09076648 -4.68176894 -0.90446066 -1.96062484 -7.86203283  8.86898519]
 [-0.10827206 -4.75925506 -0.81773823 -1.54195236 -

iteration 315 x = [[ -0.9966562   -9.02100107  -2.36995644  -0.58526363 -13.38618398
   -3.795233  ]
 [ -0.99967451  -9.1507928   -2.4010585   -0.09185734 -12.68305535
   -2.42119755]
 [ -0.99944685  -9.27593884  -2.4181154    0.10209539 -12.38811513
   -0.97386598]
 [ -0.99805983  -9.39885894  -2.42027807   0.15908724 -12.20249799
    0.55312711]
 [ -0.99637959  -9.51973687  -2.40704767   0.16798356 -11.96895592
    2.09941133]
 [ -0.99485148  -9.63812758  -2.37815025   0.13656037 -11.69380124
    3.67552597]], u = [[-0.73969706]
 [-1.85330168]
 [-1.58182641]
 [-0.21006125]
 [-0.92324335]]
iteration 320 x = [[ -0.99485148  -9.63812758  -2.37815025   0.13656037 -11.69380124
    3.67552597]
 [ -0.99082185  -9.74863284  -2.33979013   0.66913977 -10.42206827
    3.93887693]
 [ -0.98149828  -9.84693098  -2.300382     1.19323894  -9.25732617
    3.89874897]
 [ -0.9670147   -9.93418628  -2.26257792   1.70028898  -8.21385923
    3.62900147]
 [ -0.9516394  -10.01699255  -2.21835792   1.3783606

iteration 390 x = [[  0.72157232 -12.76790503   5.48536468  -0.95007915   2.48287531
    0.69611971]
 [  0.71440179 -12.74790783   5.49820934  -0.48374952   1.51857509
    1.8592802 ]
 [  0.71055441 -12.73480942   5.5187836   -0.2857107    1.10243474
    2.25093972]
 [  0.70880315 -12.72606663   5.54345546  -0.06453829   0.64712953
    2.68024659]
 [  0.7104972  -12.72433279   5.57561633   0.40334324  -0.30073407
    3.75279416]
 [  0.71390232 -12.72609719   5.61061658   0.27771196  -0.05087608
    3.24525131]], u = [[ 1.55147674]
 [ 0.41703182]
 [ 0.46695406]
 [ 1.25300611]
 [-0.28222798]]
iteration 395 x = [[  0.71390232 -12.72609719   5.61061658   0.27771196  -0.05087608
    3.24525131]
 [  0.71901871 -12.73135555   5.64852199   0.74548353  -1.002414
    4.3423722 ]
 [  0.72418699 -12.73672566   5.68488072   0.2883658   -0.0691948
    2.92277294]
 [  0.72478768 -12.73270383   5.70691188  -0.16826963   0.87473513
    1.48342122]
 [  0.72081831 -12.71921951   5.71461226  -0.62588187  

iteration 465 x = [[  0.94072032 -12.98639221   3.59674163  -1.92021303  -2.74193342
  -10.75737306]
 [  0.92034885 -13.01506128   3.486274    -2.15056364  -2.99042786
  -11.32448723]
 [  0.89730706 -13.0453055    3.36969826  -2.45388021  -3.04515422
  -11.97014125]
 [  0.87186934 -13.07640914   3.24820866  -2.63108344  -3.14699989
  -12.30384997]
 [  0.84598549 -13.10973714   3.12590803  -2.54549257  -3.48186243
  -12.14042086]
 [  0.81918466 -13.14208019   3.00363014  -2.81500584  -2.9459347
  -12.28702187]], u = [[-0.76961433]
 [-1.11342202]
 [-0.74002741]
 [-0.10917779]
 [-1.65110277]]
iteration 470 x = [[  0.81918466 -13.14208019   3.00363014  -2.81500584  -2.9459347
  -12.28702187]
 [  0.79201925 -13.17233526   2.88288813  -2.62047757  -3.07382537
  -11.85907751]
 [  0.76687555 -13.2033155    2.76654304  -2.4109899   -3.10003253
  -11.41467882]
 [  0.74421794 -13.23489356   2.65470806  -2.12319503  -3.20037176
  -10.96455618]
 [  0.72531584 -13.26890386   2.54732618  -1.65981329 

iteration 535 x = [[ -0.7057824  -14.14961624   0.75917355  -0.08939045 -10.68855606
   11.58831546]
 [ -0.70596286 -14.25485642   0.86393316   0.05736445 -10.36155468
    9.36027706]
 [ -0.70456217 -14.35683857   0.94629687   0.2261187  -10.03152366
    7.10673498]
 [ -0.70202241 -14.45597745   1.00800475   0.28394945  -9.79065144
    5.22576664]
 [ -0.69817931 -14.55176373   1.0483993    0.48788     -9.35073569
    2.83972306]
 [ -0.69219892 -14.64260501   1.06448798   0.71157155  -8.79487752
    0.36041571]], u = [[ 6.40005709]
 [ 1.28354865]
 [ 0.61968111]
 [ 1.3684443 ]
 [12.10250415]]
iteration 540 x = [[ -0.69219892 -14.64260501   1.06448798   0.71157155  -8.79487752
    0.36041571]
 [ -0.68753122 -14.73209965   1.06768525   0.21961502  -9.10855455
    0.26076927]
 [ -0.68654333 -14.8229154    1.06480672  -0.02195254  -9.045089
   -0.85958345]
 [ -0.68870651 -14.91395016   1.05249874  -0.41169082  -9.15524763
   -1.63161896]
 [ -0.69542099 -15.00690482   1.03360805  -0.93306805 

iteration 610 x = [[ 3.17429146e-01 -1.86504653e+01  1.50935659e-01  3.46745352e-01
   3.49221091e+00 -6.65381312e+00]
 [ 3.22313199e-01 -1.86182969e+01  8.81966025e-02  6.29088239e-01
   2.94481397e+00 -5.89874705e+00]
 [ 3.30835033e-01 -1.85932120e+01  3.50878699e-02  1.07382500e+00
   2.07829733e+00 -4.73522298e+00]
 [ 3.43763884e-01 -1.85766087e+01 -6.77340534e-03  1.51084847e+00
   1.24809877e+00 -3.65032392e+00]
 [ 3.61034558e-01 -1.85681492e+01 -3.81658376e-02  1.94264587e+00
   4.47984872e-01 -2.63905288e+00]
 [ 3.82608821e-01 -1.85675858e+01 -5.97323657e-02  2.37204514e+00
  -3.33229265e-01 -1.68093290e+00]], u = [[0.6251353 ]
 [5.01266292]
 [2.61149529]
 [1.83047257]
 [2.3804213 ]]
iteration 615 x = [[  0.38260882 -18.56758585  -0.05973237   2.37204514  -0.33322927
   -1.6809329 ]
 [  0.40847696 -18.5747952   -0.07186902   2.80188584  -1.10885834
   -0.74812934]
 [  0.43865701 -18.58979036  -0.07467879   3.23485812  -1.89265343
    0.18945103]
 [  0.47319268 -18.61271904  -0.

iteration 675 x = [[  0.98878725 -18.05969614  -0.2528326    0.31651731   3.52006313
   -2.79906724]
 [  0.99160289 -18.02347189  -0.28169171   0.24650862   3.72987191
   -2.98215425]
 [  0.99304107 -17.98448527  -0.3124913    0.06625078   4.03856728
   -3.15706005]
 [  0.99320829 -17.9430236   -0.34457487  -0.01865303   4.23899958
   -3.25034622]
 [  0.99285092 -17.89988872  -0.37737551  -0.04632177   4.38182956
   -3.30537914]
 [  0.99082406 -17.85443667  -0.40988886  -0.35717984   4.69932435
   -3.17490016]], u = [[ 0.91357527]
 [ 0.94293534]
 [ 0.40759564]
 [ 0.4882584 ]
 [-4.8850746 ]]
iteration 680 x = [[  0.99082406 -17.85443667  -0.40988886  -0.35717984   4.69932435
   -3.17490016]
 [  0.98574412 -17.8060873   -0.44042885  -0.65700498   4.96134802
   -2.91124707]
 [  0.98094781 -17.75678418  -0.47086312  -0.30288506   4.90732827
   -3.18978408]
 [  0.9795338  -17.70774187  -0.50431623   0.01980745   4.90780827
   -3.51201181]
 [  0.9783023  -17.65788772  -0.53684743  -0.2649309

iteration 745 x = [[  0.98624004 -13.97369191   0.38833757  -0.42816937   2.28045186
   11.5639315 ]
 [  0.98068107 -13.94947009   0.50123244  -0.68190697   2.57499392
   11.0022054 ]
 [  0.97334702 -13.92186686   0.6067445   -0.78241702   2.94908362
   10.09681526]
 [  0.96487838 -13.89048523   0.70359941  -0.90960124   3.32890258
    9.27565299]
 [  0.95596651 -13.85523419   0.79066394  -0.87055006   3.71417635
    8.14975091]
 [  0.94665138 -13.81631493   0.86861441  -0.99170298   4.06962566
    7.44352413]], u = [[-0.47588548]
 [-0.01619126]
 [-0.14164442]
 [ 0.34155744]
 [-0.17748178]]
iteration 750 x = [[  0.94665138 -13.81631493   0.86861441  -0.99170298   4.06962566
    7.44352413]
 [  0.93643382 -13.77389467   0.9390362   -1.05098719   4.41114311
    6.64753861]
 [  0.92529134 -13.72805717   1.00232933  -1.17729211   4.75659894
    6.01185079]
 [  0.9146916  -13.67950263   1.05632458  -0.94069247   4.93631124
    4.8138591 ]
 [  0.90541861 -13.62909618   1.10074619  -0.9132086

iteration 815 x = [[ 0.84942707 -9.00480049  1.38407934  1.62968269 10.11275856 10.38771223]
 [ 0.86325257 -8.90043266  1.47698347  1.13283059 10.71731256  8.26733593]
 [ 0.87620146 -8.78478368  1.53825318  1.44484456 12.31924751  4.02196079]
 [ 0.88917345 -8.65966254  1.56655777  1.14515403 12.66211068  1.68963047]
 [ 0.90165686 -8.5290515   1.56481589  1.34185229 13.39264806 -2.00143278]
 [ 0.91213364 -8.39686293  1.53884126  0.75517632 13.0465051  -3.15583459]], u = [[-17.40703989]
 [  9.48470866]
 [ -0.36403165]
 [  1.19669033]
 [ -3.94093068]]
iteration 820 x = [[  0.91213364  -8.39686293   1.53884126   0.75517632  13.0465051
   -3.15583459]
 [  0.91679904  -8.26802102   1.50231489   0.17994301  12.72962932
   -4.12500059]
 [  0.91927759  -8.13960305   1.44610415   0.31247328  12.93027749
   -7.09459883]
 [  0.92299733  -8.00972395   1.36077576   0.42944085  13.03802808
   -9.95914644]
 [  0.92580522  -7.87968883   1.2528162    0.13219354  12.98590371
  -11.63835112]
 [  0.9276388

iteration 890 x = [[ 8.40030201e-01 -1.54941862e+00 -3.78591874e-01 -2.34342453e+00
   1.40940718e+00  1.63539265e+01]
 [ 8.17045399e-01 -1.54019036e+00 -2.04416235e-01 -2.26272922e+00
   4.87092249e-01  1.83560336e+01]
 [ 7.92382127e-01 -1.53751137e+00 -1.73430747e-02 -2.67250633e+00
   1.10232432e-01  1.89408095e+01]
 [ 7.65066584e-01 -1.53665644e+00  1.71517170e-01 -2.78778649e+00
   1.39582220e-01  1.86484602e+01]
 [ 7.34978426e-01 -1.53388448e+00  3.54882337e-01 -3.22517724e+00
   4.59367027e-01  1.79516824e+01]
 [ 7.03298351e-01 -1.52556531e+00  5.24014552e-01 -3.10027515e+00
   1.22455734e+00  1.58239327e+01]], u = [[ 1.57994662]
 [-0.57645729]
 [ 0.46392368]
 [-0.74741062]
 [ 1.08766048]]
iteration 895 x = [[ 0.70329835 -1.52556531  0.52401455 -3.10027515  1.22455734 15.82393275]
 [ 0.6717814  -1.50995134  0.67443267 -3.19720987  1.90267352 14.26079878]
 [ 0.63890493 -1.4877523   0.8108694  -3.37462067  2.53888064 13.03761712]
 [ 0.60535094 -1.45885794  0.93287993 -3.33269885  

iteration 970 x = [[ 0.80340656  0.06818499  4.69462495  4.78496889 -5.16179276 10.14337169]
 [ 0.85064234  0.01729636  4.79606858  4.66210671 -5.01893967 10.14397503]
 [ 0.89495506 -0.02909848  4.8941382   4.20039894 -4.26077192  9.44560707]
 [ 0.93542002 -0.06935323  4.98613129  3.89265858 -3.78989173  8.93952315]
 [ 0.97456563 -0.10819975  5.0765941   3.93641507 -3.98108629  9.16133727]
 [ 1.00379404 -0.12921076  5.14491935  1.57945531  0.41677229  3.70051695]], u = [[-0.27018858]
 [-1.30949239]
 [-0.66835903]
 [ 0.08955571]
 [-0.06034192]]
iteration 975 x = [[ 1.00379404 -0.12921076  5.14491935  1.57945531  0.41677229  3.70051695]
 [ 1.01204497 -0.11088098  5.16371965  0.26707844  2.87520865  0.54362373]
 [ 1.01160211 -0.07643159  5.16203407 -0.26091265  3.83271997 -0.64080451]
 [ 1.00692602 -0.03443992  5.15153381 -0.67436623  4.56394265 -1.43594545]
 [ 0.99796696  0.01507835  5.13354536 -1.11716972  5.33618217 -2.13054983]
 [ 0.98884813  0.06434062  5.1172259  -0.70690047  4.5223

iteration 1055 x = [[  0.932147     3.77462428   5.83755333   1.19004572  12.94710055
  -14.00505903]
 [  0.94460421   3.90073565   5.71174823   1.30264618  12.27434077
  -11.13938125]
 [  0.95823144   4.02014506   5.61480744   1.42440083  11.60882534
   -8.25346725]
 [  0.97312242   4.13289668   5.54654148   1.55517331  10.93788709
   -5.40624761]
 [  0.98936012   4.23876752   5.50658352   1.69351703  10.22640238
   -2.58806786]
 [  1.00093396   4.33587557   5.48361267   0.56722229   9.22015986
   -2.20534138]], u = [[ 1.07244627]
 [ 1.32117425]
 [ 1.1460801 ]
 [ 1.45563494]
 [-3.62835806]]
iteration 1060 x = [[ 1.00093396  4.33587557  5.48361267  0.56722229  9.22015986 -2.20534138]
 [ 1.00345857  4.42442591  5.46565338  0.02172309  8.51819733 -1.27763696]
 [ 1.00243338  4.50646146  5.45955741 -0.18580431  7.89045597  0.12362109]
 [ 1.00023675  4.58215404  5.46893194 -0.23493521  7.24063051  1.78415284]
 [ 0.99793949  4.65110211  5.49559366 -0.21716129  6.53956639  3.56173707]
 [ 0.99

iteration 1135 x = [[ 0.60442855  8.5693116   5.44952227  1.94898725  9.00860424 -5.94532478]
 [ 0.62646218  8.66258448  5.3890235   2.46092822  9.64858247 -6.11643087]
 [ 0.65265573  8.76047224  5.33155555  2.77784705  9.92480944 -5.34302257]
 [ 0.68133741  8.85973707  5.2850685   2.95634648  9.91711262 -3.92500631]
 [ 0.71241051  8.95979649  5.25160982  3.25676824 10.08074224 -2.72255024]
 [ 0.74760945  9.06322576  5.22819034  3.7823201  10.58699232 -1.88704835]], u = [[1.02840136]
 [0.47751278]
 [0.15289697]
 [0.46771668]
 [1.19156804]]
iteration 1140 x = [[ 0.74760945  9.06322576  5.22819034  3.7823201  10.58699232 -1.88704835]
 [ 0.7834969   9.1624338   5.22743855  3.38733696  9.22057204  1.71810691]
 [ 0.81522015  9.24695972  5.26219215  2.9515824   7.65222927  5.21640065]
 [ 0.84243389  9.31486669  5.33152032  2.48737125  5.90094542  8.64278188]
 [ 0.86490739  9.36445231  5.43509009  2.0049842   3.99165728 12.08388961]
 [ 0.88249685  9.3942308   5.5737074   1.51150528  1.9417750

iteration 1215 x = [[ 0.19916299 11.47406012  8.10739395 -1.92260637 -0.85419586  3.89933276]
 [ 0.17991911 11.46495285  8.14748988 -1.92617673 -0.96683681  4.11894022]
 [ 0.16212661 11.4531011   8.18810801 -1.63277926 -1.40598978  4.0036311 ]
 [ 0.14691388 11.4371635   8.22790555 -1.41026864 -1.78302854  3.95365668]
 [ 0.13461658 11.41663146  8.2663174  -1.05017759 -2.32496864  3.7240524 ]
 [ 0.12589538 11.39063543  8.30226351 -0.69529456 -2.87469771  3.45840336]], u = [[-0.0420577 ]
 [ 0.78713964]
 [ 0.5973224 ]
 [ 0.99588492]
 [ 1.03530241]]
iteration 1220 x = [[ 0.12589538 11.39063543  8.30226351 -0.69529456 -2.87469771  3.45840336]
 [ 0.11965602 11.36024771  8.33659471 -0.55337314 -3.20311542  3.40312843]
 [ 0.11445021 11.32694918  8.37068983 -0.48843733 -3.4571141   3.41217655]
 [ 0.110618   11.2903341   8.40376843 -0.27923243 -3.86533909  3.19665394]
 [ 0.10673254 11.25172634  8.43742085 -0.49771029 -3.85896466  3.53514561]
 [ 0.10063046 11.21313506  8.47454486 -0.72256518 -3.86

iteration 1295 x = [[-0.96106618  6.82573599 12.35299565 -0.41598763 -0.9314923   1.65257412]
 [-0.96727052  6.82030461 12.36519074 -0.8252475  -0.15320683  0.78261672]
 [-0.97762686  6.8227662  12.36853921 -1.24584132  0.64485842 -0.11162682]
 [-0.99215826  6.83313429 12.36306648 -1.31214238  0.88309434 -0.45280421]
 [-1.00001464  6.83442324 12.36524448 -0.3867887  -0.42494838  0.6935868 ]
 [-1.00145451  6.82704468 12.37466176  0.03147356 -0.94669     1.09129862]], u = [[-0.97295445]
 [-1.13225051]
 [-0.98997296]
 [-3.52461466]
 [ 0.06399646]]
iteration 1300 x = [[-1.00145451  6.82704468 12.37466176  0.03147356 -0.94669     1.09129862]
 [-1.00008852  6.81656768 12.38606144  0.22857335 -1.1292304   1.17149021]
 [-0.99642809  6.8036961  12.39891977  0.50402776 -1.44800988  1.40650949]
 [-0.99287775  6.79228484 12.40933196  0.23698809 -0.8844126   0.72700245]
 [-0.99048265  6.78400998 12.41557664  0.24202674 -0.77093445  0.52270108]
 [-0.98784759  6.77654056 12.42014471  0.28503047 -0.72

iteration 1375 x = [[-0.3919153   9.60598388  9.42695212  3.50097203 14.04372939 -4.12949277]
 [-0.35709072  9.74569405  9.38588117  3.4512587  13.85825364 -4.08825364]
 [-0.3223684   9.88385661  9.34399549  3.48147619 13.73626223 -4.29338117]
 [-0.28703485 10.02083073  9.29895317  3.5745414  13.62136136 -4.7221566 ]
 [-0.25084976 10.15594189  9.24905777  3.65489264 13.37052479 -5.26816953]
 [-0.21618706 10.28516516  9.19662778  3.28219778 12.48893635 -5.23213519]], u = [[ 0.22516819]
 [ 0.57501792]
 [ 0.89055213]
 [ 2.06605019]
 [-0.2318349 ]]
iteration 1380 x = [[-0.21618706 10.28516516  9.19662778  3.28219778 12.48893635 -5.23213519]
 [-0.18380988 10.40722073  9.14213023  3.19437695 11.91876165 -5.67868012]
 [-0.15155311 10.52393914  9.08170861  3.25802412 11.41450611 -6.41645064]
 [-0.11871029 10.63530235  9.01375731  3.3135     10.85202225 -7.18325778]
 [-0.08511073 10.74088863  8.93771324  3.41060825 10.26073821 -8.0326605 ]
 [-0.05040381 10.84045565  8.85299173  3.53591379  9.65

iteration 1455 x = [[ 1.0052264  16.74073615  8.36047527 -0.41043315  9.26360672  1.71288213]
 [ 1.00138922 16.83354456  8.37151254 -0.35026043  9.28272642  0.48786923]
 [ 0.99644528 16.92550217  8.37488378 -0.6376179   9.11274875  0.19225534]
 [ 0.9878605  17.01578664  8.37735364 -1.07781695  8.95759689  0.30040437]
 [ 0.97825525 17.10476392  8.37321298 -0.84395138  8.81641493 -1.11010092]
 [ 0.97097892 17.19174071  8.35551153 -0.6108992   8.56280823 -2.41261258]], u = [[ 0.68028628]
 [-0.52968547]
 [-2.11863547]
 [ 2.22393396]
 [ 3.75655554]]
iteration 1460 x = [[ 0.97097892 17.19174071  8.35551153 -0.6108992   8.56280823 -2.41261258]
 [ 0.96272749 17.27687345  8.33210116 -1.0387064   8.4766127  -2.27586425]
 [ 0.95021359 17.36152571  8.30983911 -1.46386998  8.46630304 -2.18569744]
 [ 0.93344945 17.44644618  8.28817536 -1.889225    8.53004153 -2.15916237]
 [ 0.91582822 17.52980631  8.26097048 -1.63269556  8.12940632 -3.26066095]
 [ 0.90084775 17.60881898  8.22338581 -1.36058041  7.66

iteration 1535 x = [[ 0.91159372 21.20099612  4.14741721 -1.23174531  8.23387957  5.88976668]
 [ 0.90143431 21.28364367  4.20570653 -0.7980191   8.30519049  5.77934655]
 [ 0.89166671 21.36220312  4.27343184 -1.16157834  7.35990705  7.77777987]
 [ 0.88220854 21.43568352  4.3509998  -0.72828352  7.34250409  7.75237342]
 [ 0.87290344 21.50274471  4.43956676 -1.13779766  6.02663396  9.97048699]
 [ 0.86368116 21.5623739   4.53967771 -0.70526333  5.90256806 10.07400147]], u = [[ 1.67194403]
 [-2.46044294]
 [ 1.98273676]
 [-5.61973379]
 [ 2.10356781]]
iteration 1540 x = [[ 0.86368116 21.5623739   4.53967771 -0.70526333  5.90256806 10.07400147]
 [ 0.85442802 21.61338277  4.6526249  -1.1486358   4.26450814 12.53110413]
 [ 0.84510647 21.65487461  4.77941895 -0.71455735  4.03384401 12.85883672]
 [ 0.83566185 21.68583251  4.92199258 -1.17575069  2.12826257 15.69738301]
 [ 0.82158021 21.6968577   5.09453942 -1.64019998  0.04633821 18.89254679]
 [ 0.8028886  21.68608188  5.30199577 -2.09487036 -2.24

iteration 1605 x = [[ 0.85183694 24.66334315  5.94776686 -1.54977817  2.81580726  0.52028597]
 [ 0.83672006 24.69025844  5.95459577 -1.47327536  2.56796056  0.84240096]
 [ 0.82112333 24.71728852  5.96068048 -1.64659059  2.83991102  0.37455819]
 [ 0.8037895  24.74706941  5.96212556 -1.82074842  3.11819295 -0.08543825]
 [ 0.78453318 24.78002834  5.95848309 -2.03125887  3.47565903 -0.6420373 ]
 [ 0.76293301 24.81707054  5.94866792 -2.28972363  3.93483297 -1.31806483]], u = [[ 0.16159656]
 [-0.42285463]
 [-0.41719051]
 [-0.49158463]
 [-0.58885416]]
iteration 1610 x = [[ 0.76293301 24.81707054  5.94866792 -2.28972363  3.93483297 -1.31806483]
 [ 0.73885008 24.85849162  5.93258186 -2.52768117  4.35092753 -1.89494375]
 [ 0.71584521 24.89688364  5.92093511 -2.07182037  3.32944255 -0.45124121]
 [ 0.69388195 24.93251526  5.91308899 -2.32143731  3.79761057 -1.11253429]
 [ 0.6683707  24.97498405  5.89594301 -2.78177163  4.69475981 -2.2991599 ]
 [ 0.6428739  25.01682551  5.87998956 -2.31682958  3.67

iteration 1685 x = [[ 0.24473736 26.7356214   5.01537301  1.44839624  6.19156638 -6.89257219]
 [ 0.26118483 26.7987947   4.94338254  1.84228286  6.4480493  -7.50214329]
 [ 0.28160835 26.86468669  4.86541042  2.24377415  6.73592096 -8.08766055]
 [ 0.3060892  26.93363344  4.78173381  2.65394222  7.060011   -8.64184491]
 [ 0.33472042 27.00603208  4.69270213  3.07409482  7.42780678 -9.15743053]
 [ 0.36760998 27.08237081  4.59874017  3.50593978  7.85017254 -9.62646622]], u = [[2.72498216]
 [1.5756091 ]
 [1.35875953]
 [1.06064884]
 [2.95972626]]
iteration 1690 x = [[  0.36760998  27.08237081   4.59874017   3.50593978   7.85017254
   -9.62646622]
 [  0.4048858   27.16326734   4.50035979   3.95179854   8.34233884
  -10.03928726]
 [  0.44336919  27.24724788   4.40723727   3.74485717   8.45875979
   -8.58574863]
 [  0.48090191  27.3333681    4.32566917   3.762675     8.77199391
   -7.72058388]
 [  0.51722228  27.42154899   4.25673248   3.50015638   8.85842964
   -6.06219836]
 [  0.55258544  27.5

iteration 1765 x = [[-1.23822239e-01  2.57530364e+01  1.20511783e+01 -3.03395322e-01
  -3.89048689e+00  7.49076211e+00]
 [-1.25231862e-01  2.57124298e+01  1.21267231e+01  2.26242941e-02
  -4.23873029e+00  7.63863117e+00]
 [-1.23602604e-01  2.56684444e+01  1.22041721e+01  3.04459450e-01
  -4.56651726e+00  7.87088676e+00]
 [-1.20723109e-01  2.56233466e+01  1.22825965e+01  2.70931811e-01
  -4.45081848e+00  7.80599532e+00]
 [-1.16494776e-01  2.55767100e+01  1.23627907e+01  5.76447586e-01
  -4.88646214e+00  8.25511677e+00]
 [-1.08556189e-01  2.55243623e+01  1.24492878e+01  1.01418924e+00
  -5.59785158e+00  9.07550438e+00]], u = [[ 0.81591656]
 [ 0.68524774]
 [-0.11037388]
 [ 0.71482646]
 [ 1.1800033 ]]
iteration 1770 x = [[-0.10855619 25.52436229 12.44928779  1.01418924 -5.59785158  9.07550438]
 [-0.09615034 25.46447232 12.54484722  1.47001465 -6.39249006 10.05709873]
 [-0.08276915 25.40356448 12.64135835  1.20284856 -5.77570681  9.21274641]
 [-0.07213997 25.3491301  12.72869225  0.92054575

iteration 1835 x = [[-0.46412869 20.82326181 16.18866795 -1.78467262 -8.27428071  5.75499059]
 [-0.48112973 20.74284437 16.24675971 -1.61836075 -7.81719276  5.86294238]
 [-0.49661071 20.6667694  16.30602253 -1.48033772 -7.40462636  5.98846716]
 [-0.51078703 20.59462262 16.36650634 -1.35714484 -7.03090027  6.10659435]
 [-0.52366049 20.52598828 16.42787463 -1.21943113 -6.70209958  6.16516836]
 [-0.53498025 20.46035981 16.48936316 -1.04598788 -6.42984023  6.13094176]], u = [[0.1343779 ]
 [0.09510121]
 [0.09292358]
 [0.17822528]
 [0.32277748]]
iteration 1840 x = [[-0.53498025 20.46035981 16.48936316 -1.04598788 -6.42984023  6.13094176]
 [-0.54419846 20.39704704 16.54975664 -0.79856002 -6.23940365  5.94735851]
 [-0.5527162  20.33656945 16.61124339 -0.90705052 -5.85812164  6.34445302]
 [-0.56044077 20.2784622  16.67338017 -0.63812172 -5.76865192  6.08390556]
 [-0.56735689 20.22254611 16.73588209 -0.74684662 -5.41676116  6.41057096]
 [-0.57589848 20.17047969 16.80221021 -0.96347435 -4.9988111

iteration 1915 x = [[-0.88222076 18.79674575 18.97634239  1.41964541 -3.01584713  2.71835478]
 [-0.87034081 18.7712121  18.9978516   0.95698924 -2.09603832  1.59637988]
 [-0.86306891 18.75473422 19.0084952   0.49791276 -1.20327424  0.54151428]
 [-0.85786644 18.74203099 19.01505015  0.54265785 -1.33790183  0.77009673]
 [-0.85437006 18.73229388 19.01861284  0.15694214 -0.61163189 -0.05262629]
 [-0.85326807 18.7268533  19.01762665  0.06353907 -0.47693391 -0.14389352]], u = [[-2.45653988]
 [-1.47552944]
 [ 0.08314611]
 [-0.85005398]
 [-0.21969058]]
iteration 1920 x = [[-0.85326807 18.7268533  19.01762665  0.06353907 -0.47693391 -0.14389352]
 [-0.85384408 18.72424275 19.01391931 -0.17866668 -0.0455153  -0.5970483 ]
 [-0.8578881  18.7280449  19.00310237 -0.63026302  0.80696878 -1.56917875]
 [-0.86646189 18.74043754 18.98241044 -1.08491958  1.67459982 -2.57694332]
 [-0.87765847 18.75767414 18.95629386 -1.15460408  1.77450631 -2.65053091]
 [-0.8887601  18.77433228 18.93137188 -1.0658151   1.55

iteration 1995 x = [[ -0.74925706  15.80186874  20.23620245  -1.57205522  -4.92742197
  -11.30830822]
 [ -0.76563505  15.75656699  20.11501616  -1.70221485  -4.10964996
  -12.97137355]
 [ -0.78263848  15.72135738  19.97452707  -1.697093    -2.90659609
  -15.17889627]
 [ -0.80170879  15.69492103  19.81448207  -2.11533532  -2.35068444
  -16.91383468]
 [ -0.82026874  15.68376289  19.62497844  -1.59496035   0.1551496
  -21.09272325]
 [ -0.83357794  15.6987733   19.39003548  -1.06628841   2.87740101
  -26.02773196]], u = [[-0.34311449]
 [-0.06911172]
 [-2.50292792]
 [ 2.1322218 ]
 [ 1.66104614]]


# Rollouts

In [8]:
multi_evaluate(env, dynamics, x0s, us)

performance
receding_performance


rewards  lengths
performance            935.548815      100
receding_performance  1869.756658      200