In [1]:
from ilqr import iLQR
import gym
import numpy as np
import pandas as pd
import time

from aprl.agents import MujocoFiniteDiffDynamicsPerformance
from aprl.envs.mujoco_costs import get_cost
from experiments.common import set_seeds, make_env, fit_ilqr, \
                               on_iteration, receding, multi_evaluate

WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'


Logging to /tmp/openai-2019-02-02-13-05-32-235612
Choosing the latest nvidia driver: /usr/lib/nvidia-396, among ['/usr/lib/nvidia-375', '/usr/lib/nvidia-396']
Choosing the latest nvidia driver: /usr/lib/nvidia-396, among ['/usr/lib/nvidia-375', '/usr/lib/nvidia-396']


In [3]:
seed = 42
set_seeds(seed)

short_horizon = 50

env_name = 'InvertedPendulum-v2'
env, us_init = make_env(env_name, seed=seed, horizon=short_horizon)
dynamics = {'performance': MujocoFiniteDiffDynamicsPerformance(env)}
x0s = {k: dyn.get_state() for k, dyn in dynamics.items()}

costs = {k: get_cost(env_name) for k in dynamics.keys()}
ilqrs = {k: iLQR(dyn, costs[k], len(us_init))  
         for k, dyn in dynamics.items()}

# Open Loop

In [4]:
xs, us = fit_ilqr(ilqrs, x0s, us_init)

dict_keys(['performance'])
*** Fitting performance ***
iteration -1 converged 98.62615632028051 [-0.99884302  1.59168136 -2.18710654 -0.3509489 ] [-1.8908733]
iteration 0 accepted 55.08667724518653 [-0.33604464  1.63644166 -0.89895013 -0.73787982] [-0.7717686]
iteration 1 accepted 35.76847230409324 [-0.13107992  1.42375244 -0.2625448   5.35706429] [-0.18044272]
iteration 2 accepted 0.8206971341260431 [-0.01531407 -0.21129975 -0.23706047 -0.49392843] [-0.2426436]
iteration 3 accepted 0.001890966644626577 [0.01087307 0.00653197 0.02728976 0.01338608] [0.01333365]
iteration 4 accepted 0.0007434571828886829 [ 0.00736889 -0.0003039   0.00882465  0.00482244] [0.00054285]
iteration 5 accepted 0.0007434233101104847 [ 0.00736403 -0.00027667  0.00880865  0.00494782] [0.00054287]
iteration 6 accepted 0.0007434171863289613 [ 0.00735939 -0.00025028  0.00879359  0.00506883] [0.000543]
iteration 7 failed 0.0007434171863289614 [ 0.00735939 -0.00025028  0.00879359  0.00506883] [0.000543]
iteration 8 fa

# Closed Loop

In [7]:
for k, ilqr in ilqrs.items():
    underlying = 'receding_' + k
    dynamics[underlying] = dynamics[k]
    x0s[underlying] = x0s[k]
    xs[underlying], us[underlying] = receding(ilqr, x0s[k], us_init, seed=seed,
                                              horizon=5000, step_size=10)

iteration 0 x = [[-2.51713244e-03 -3.13228967e-04  8.41541642e-03 -3.61090414e-04]
 [-2.32565312e-03 -3.68820468e-04  1.07288464e-02 -5.16754091e-03]
 [-2.09773844e-03 -4.96166785e-04  1.20617967e-02 -7.56206461e-03]
 [-1.84926242e-03 -6.56889860e-04  1.27865811e-02 -8.51945364e-03]
 [-1.59002365e-03 -8.28407090e-04  1.31389109e-02 -8.64882617e-03]
 [-1.32602972e-03 -9.97855039e-04  1.32624879e-02 -8.31580526e-03]
 [-1.06098408e-03 -1.15817013e-03  1.32442101e-02 -7.73647094e-03]
 [-7.97193649e-04 -1.30570811e-03  1.31369475e-02 -7.03769756e-03]
 [-5.36111488e-04 -1.43882747e-03  1.29732805e-02 -6.29348464e-03]
 [-2.78661014e-04 -1.55704939e-03  1.27736339e-02 -5.54645954e-03]
 [-2.54307978e-05 -1.66055897e-03  1.25510901e-02 -4.82059295e-03]], u = [[ 0.01313067]
 [ 0.00789967]
 [ 0.00461073]
 [ 0.00255733]
 [ 0.00126136]
 [ 0.00042706]
 [-0.000123  ]
 [-0.00049485]
 [-0.00075221]
 [-0.00093381]]
iteration 10 x = [[-2.54307978e-05 -1.66055897e-03  1.25510901e-02 -4.82059295e-03]
 [ 2.2

iteration 160 x = [[-0.02019403 -0.0023054   0.03482677 -0.09538011]
 [-0.01967397 -0.00377123  0.01723194 -0.05168222]
 [-0.0194475  -0.0045204   0.0054476  -0.02352293]
 [-0.01942521 -0.00479247 -0.0031988  -0.0038605 ]
 [-0.0195588  -0.00471857 -0.01014755  0.01114527]
 [-0.01982213 -0.0043704  -0.01617788  0.02361424]
 [-0.02020112 -0.00378654 -0.02171725  0.03474774]
 [-0.02068837 -0.0029865  -0.02700745  0.04525976]
 [-0.02128034 -0.00197813 -0.03219116  0.05560267]
 [-0.02197577 -0.00076177 -0.03735462  0.06607997]
 [-0.02277473  0.00066737 -0.04254753  0.07690087]], u = [[-0.09363259]
 [-0.06358602]
 [-0.04745956]
 [-0.03880156]
 [-0.03415327]
 [-0.03167638]
 [-0.03040279]
 [-0.02981693]
 [-0.02962492]
 [-0.02963539]]
iteration 170 x = [[-0.02277473  0.00066737 -0.04254753  0.07690087]
 [-0.02346757  0.00182025 -0.02678138  0.03879226]
 [-0.02388932  0.00233192 -0.01542204  0.01262349]
 [-0.02410767  0.00238638 -0.0064307  -0.00702336]
 [-0.02415899  0.00208412  0.00128753 -0.0

iteration 320 x = [[-0.00622429 -0.01003011  0.12876614 -0.1369353 ]
 [-0.00388478 -0.0122106   0.10525574 -0.08175368]
 [-0.00194866 -0.0134715   0.08840238 -0.04474579]
 [-0.00031343 -0.01409432  0.07515071 -0.01780365]
 [ 0.00107648 -0.0142356   0.06386118  0.00349882]
 [ 0.0022515  -0.01398344  0.05365487  0.02160536]
 [ 0.00322856 -0.0133878   0.04405938  0.03789603]
 [ 0.00401729 -0.0124768   0.0348182   0.05318236]
 [ 0.00462336 -0.01126539  0.02578967  0.06797057]
 [ 0.00505024 -0.00976017  0.01689618  0.08259543]
 [ 0.00530026 -0.00796209  0.00809976  0.09728633]], u = [[-0.1266465 ]
 [-0.09252918]
 [-0.07428286]
 [-0.06449763]
 [-0.05919576]
 [-0.05625428]
 [-0.05454871]
 [-0.05348291]
 [-0.05272518]
 [-0.0520699 ]]
iteration 330 x = [[ 0.00530026 -0.00796209  0.00809976  0.09728633]
 [ 0.00558699 -0.00636859  0.02052784  0.06248843]
 [ 0.00609143 -0.00538061  0.0298835   0.03660449]
 [ 0.00676711 -0.0048607   0.03766093  0.01559696]
 [ 0.0075904  -0.00473367  0.04465075 -0.0

iteration 480 x = [[ 0.00791764 -0.00511059  0.0699558  -0.10710995]
 [ 0.00912532 -0.00678529  0.05087047 -0.0608802 ]
 [ 0.010006   -0.00768586  0.03723432 -0.02950501]
 [ 0.01064326 -0.00804146  0.02651595 -0.00626683]
 [ 0.0110818  -0.00797767  0.0173541   0.01251022]
 [ 0.01134539 -0.0075631   0.00901545  0.0288665 ]
 [ 0.01144651 -0.00683439  0.00110238  0.04396533]
 [ 0.01139149 -0.00580972 -0.00660242  0.05849716]
 [ 0.0111833  -0.00449609 -0.0142176   0.07289318]
 [ 0.01082312 -0.00289337 -0.02180423  0.08743404]
 [ 0.01031123 -0.00099667 -0.02939213  0.10231924]], u = [[-0.10210161]
 [-0.07415678]
 [-0.05936203]
 [-0.05159247]
 [-0.04756327]
 [-0.04552055]
 [-0.04452356]
 [-0.04405816]
 [-0.04382337]
 [-0.04365552]]
iteration 490 x = [[ 1.03112271e-02 -9.96673294e-04 -2.93921273e-02  1.02319237e-01]
 [ 9.89717219e-03  6.12433148e-04 -1.20676761e-02  5.90816423e-02]
 [ 9.77610492e-03  1.50323591e-03 -7.34311969e-05  3.03066066e-02]
 [ 9.86639824e-03  1.89843355e-03  9.08033342

iteration 640 x = [[ 0.15293998 -0.0180878   0.02053497 -0.07151231]
 [ 0.15302855 -0.01881234 -0.01160889 -0.0015437 ]
 [ 0.15259762 -0.01845268 -0.03145374  0.03725289]
 [ 0.15183731 -0.01748624 -0.04456657  0.0593228 ]
 [ 0.15085196 -0.01616825 -0.0539699   0.07251152]
 [ 0.14969921 -0.01463303 -0.0613129   0.08110248]
 [ 0.14841116 -0.01294867 -0.06750381  0.08745751]
 [ 0.14700575 -0.01114653 -0.07305     0.09289976]
 [ 0.14549302 -0.00923726 -0.07823819  0.09818279]
 [ 0.1438785  -0.0072197  -0.083229    0.10373811]
 [ 0.14216529 -0.00508594 -0.08810886  0.10981144]], u = [[-0.17873677]
 [-0.11382157]
 [-0.07806459]
 [-0.05813683]
 [-0.04684387]
 [-0.04030398]
 [-0.0364166 ]
 [-0.03402383]
 [-0.03246168]
 [-0.03133638]]
iteration 650 x = [[ 0.14216529 -0.00508594 -0.08810886  0.10981144]
 [ 0.1405431  -0.00326826 -0.07416113  0.07242337]
 [ 0.1391726  -0.00211461 -0.06292672  0.04327919]
 [ 0.13801265 -0.00149662 -0.05309616  0.01876714]
 [ 0.1370421  -0.00134186 -0.04397912 -0.0

iteration 800 x = [[-9.55833974e-04 -2.47078086e-03  5.18937136e-02 -1.09031672e-01]
 [-1.06376854e-04 -4.17823891e-03  3.31104260e-02 -6.22411789e-02]
 [ 4.24924968e-04 -5.10729733e-03  2.00566928e-02 -3.09951512e-02]
 [ 7.25993284e-04 -5.49770106e-03  1.00741337e-02 -8.25651217e-03]
 [ 8.43855613e-04 -5.48061129e-03  1.72783208e-03  9.83102910e-03]
 [ 8.03430315e-04 -5.12736209e-03 -5.76031056e-03  2.54128727e-02]
 [ 6.17602753e-04 -4.47567253e-03 -1.28166384e-02  3.97154651e-02]
 [ 2.92640653e-04 -3.54377555e-03 -1.96772043e-02  5.34667172e-02]
 [-1.68835199e-04 -2.33818006e-03 -2.64710129e-02  6.71144216e-02]
 [-7.66138655e-04 -8.58124768e-04 -3.32627430e-02  8.09398062e-02]
 [-1.49949223e-03  9.01788289e-04 -4.00787139e-02  9.51265150e-02]], u = [[-0.09970637]
 [-0.07025593]
 [-0.05462832]
 [-0.04641953]
 [-0.04219411]
 [-0.04011429]
 [-0.03918699]
 [-0.03885328]
 [-0.03877591]
 [-0.03875238]]
iteration 810 x = [[-0.00149949  0.00090179 -0.04007871  0.09512651]
 [-0.00212904  0.00

iteration 960 x = [[-3.53597110e-02  7.05966173e-04  9.44397472e-04 -1.16813939e-01]
 [-3.55553592e-02 -1.07843271e-03 -2.04434378e-02 -6.22188982e-02]
 [-3.61043528e-02 -1.97089941e-03 -3.44164531e-02 -2.73809498e-02]
 [-3.68928463e-02 -2.27529509e-03 -4.44087981e-02 -3.27086929e-03]
 [-3.78597737e-02 -2.15650649e-03 -5.22692887e-02  1.50246532e-02]
 [-3.89724944e-02 -1.70355225e-03 -5.89943235e-02  3.02035214e-02]
 [-4.02137273e-02 -9.63484680e-04 -6.51249156e-02  4.37776692e-02]
 [-4.15745923e-02  4.05086460e-05 -7.09609535e-02  5.66288151e-02]
 [-4.30509300e-02  1.29949325e-03 -7.66750638e-02  6.93045202e-02]
 [-4.46413348e-02  2.81363344e-03 -8.23702244e-02  8.21694094e-02]
 [-4.63460467e-02  4.58930312e-03 -8.81082013e-02  9.54812551e-02]], u = [[-0.1131471 ]
 [-0.07474063]
 [-0.05423602]
 [-0.04333066]
 [-0.03756219]
 [-0.03454855]
 [-0.03303029]
 [-0.03234395]
 [-0.0321266 ]
 [-0.0321625 ]]
iteration 970 x = [[-0.04634605  0.0045893  -0.0881082   0.09548126]
 [-0.04790773  0.00

iteration 1120 x = [[-4.76945128e-02 -5.09163358e-03  8.05763468e-02 -9.02168607e-02]
 [-4.62259621e-02 -6.54778806e-03  6.63239699e-02 -5.58072856e-02]
 [-4.50152789e-02 -7.39673029e-03  5.47764210e-02 -2.93734296e-02]
 [-4.40213153e-02 -7.76224468e-03  4.46431674e-02 -7.38147088e-03]
 [-4.32226420e-02 -7.71343478e-03  3.52409246e-02  1.21203375e-02]
 [-4.26082533e-02 -7.28891801e-03  2.62095855e-02  3.02383294e-02]
 [-4.21726412e-02 -6.50971297e-03  1.73589067e-02  4.76312218e-02]
 [-4.19132142e-02 -5.38605228e-03  8.58717600e-03  6.47217696e-02]
 [-4.18289344e-02 -3.92101936e-03 -1.59452436e-04  8.18038377e-02]
 [-4.19195489e-02 -2.11261057e-03 -8.90573131e-03  9.90933728e-02]
 [-4.21851128e-02  4.50014962e-05 -1.76578156e-02  1.16757558e-01]], u = [[-0.07604656]
 [-0.06266558]
 [-0.05590931]
 [-0.05260141]
 [-0.05105393]
 [-0.05038209]
 [-0.05012678]
 [-0.05004075]
 [-0.04997338]
 [-0.04982758]]
iteration 1130 x = [[-4.21851128e-02  4.50014962e-05 -1.76578156e-02  1.16757558e-01]
 

iteration 1280 x = [[ 0.10676175 -0.00614427  0.0861237  -0.1126203 ]
 [ 0.10828884 -0.00792303  0.06664498 -0.06579165]
 [ 0.10948472 -0.00892499  0.05298074 -0.03474114]
 [ 0.11043886 -0.00939414  0.04245793 -0.01239145]
 [ 0.11119968 -0.00946549  0.03364112  0.00511747]
 [ 0.11179358 -0.00921428  0.02575871  0.0199165 ]
 [ 0.11223502 -0.00868253  0.01839225  0.03321279]
 [ 0.11253201 -0.00789304  0.01130955  0.04572305]
 [ 0.11268888 -0.00685694  0.00437748  0.05790082]
 [ 0.11270787 -0.00557783 -0.0024813   0.07005095]
 [ 0.11259    -0.00405408 -0.00931001  0.08238792]], u = [[-0.1043189 ]
 [-0.07443873]
 [-0.05845597]
 [-0.04989208]
 [-0.04527504]
 [-0.04276032]
 [-0.04137789]
 [-0.04061339]
 [-0.04017787]
 [-0.0398937 ]]
iteration 1290 x = [[ 0.11259    -0.00405408 -0.00931001  0.08238792]
 [ 0.11257338 -0.00284202  0.00759777  0.03926531]
 [ 0.11284188 -0.00234897  0.01922253  0.01030781]
 [ 0.11331454 -0.00235739  0.02802459 -0.01099054]
 [ 0.11394818 -0.00275004  0.03532882 -0

iteration 1440 x = [[ 0.12389566 -0.01282801  0.06134951 -0.11632331]
 [ 0.12484558 -0.01451775  0.03371502 -0.0533001 ]
 [ 0.12533586 -0.01519307  0.01535504 -0.01459387]
 [ 0.12550944 -0.01522794  0.00202561  0.01091049]
 [ 0.12544387 -0.01482515 -0.00856968  0.02927064]
 [ 0.12518133 -0.01409389 -0.01767875  0.04381891]
 [ 0.12474467 -0.01309157 -0.02598569  0.05642004]
 [ 0.12414615 -0.01184635 -0.03386829  0.06814086]
 [ 0.12339218 -0.01036955 -0.04153362  0.07960456]
 [ 0.12248601 -0.00866255 -0.04909131  0.09118283]
 [ 0.12142919 -0.00672067 -0.05659947  0.10311543]], u = [[-0.15111386]
 [-0.10279377]
 [-0.07662667]
 [-0.06241505]
 [-0.05467063]
 [-0.05044383]
 [-0.04813249]
 [-0.04684314]
 [-0.04606412]
 [-0.0455246 ]]
iteration 1450 x = [[ 0.12142919 -0.00672067 -0.05659947  0.10311543]
 [ 0.1203832  -0.00491497 -0.04803987  0.07782862]
 [ 0.11950368 -0.00358813 -0.03994576  0.05516218]
 [ 0.11878442 -0.00269804 -0.03200781  0.03409593]
 [ 0.1182238  -0.00221876 -0.02407606  0

iteration 1600 x = [[ 0.10969514 -0.00220806  0.04114026 -0.11464491]
 [ 0.11031738 -0.00399623  0.02114576 -0.06473084]
 [ 0.11060193 -0.00495591  0.00734887 -0.03158485]
 [ 0.1106439  -0.00534553 -0.00312777 -0.00759818]
 [ 0.11049411 -0.00530624 -0.01183407  0.01138823]
 [ 0.1101796  -0.00491475 -0.01960739  0.02767859]
 [ 0.10971443 -0.00421174 -0.02690398  0.04258231]
 [ 0.10910561 -0.00321714 -0.03397564  0.05687332]
 [ 0.10835624 -0.00193835 -0.04096163  0.07103044]
 [ 0.10746731 -0.00037495 -0.04793616  0.08536299]
 [ 0.10643866  0.00147869 -0.0549353   0.10008229]], u = [[-0.10619872]
 [-0.07430516]
 [-0.05737912]
 [-0.04847094]
 [-0.04385276]
 [-0.04153283]
 [-0.04044403]
 [-0.03999918]
 [-0.0398582 ]
 [-0.03982054]]
iteration 1610 x = [[ 0.10643866  0.00147869 -0.0549353   0.10008229]
 [ 0.10557017  0.00292186 -0.03197698  0.04479846]
 [ 0.10508835  0.0034534  -0.01624176  0.00868231]
 [ 0.10488205  0.00336818 -0.00440986 -0.01701952]
 [ 0.10489114  0.00282621  0.00530681 -0

iteration 1760 x = [[ 0.10677197 -0.01028484  0.03188521 -0.09750174]
 [ 0.10715329 -0.0116407   0.0063125  -0.03866742]
 [ 0.10711701 -0.01206502 -0.00990595 -0.00406923]
 [ 0.10680731 -0.01192981 -0.02104569  0.01744182]
 [ 0.10630251 -0.01143543 -0.02942612  0.03193707]
 [ 0.1056451  -0.01068848 -0.03631335  0.04275195]
 [ 0.10485791 -0.00974376 -0.04240702  0.05174916]
 [ 0.10395289 -0.00862687 -0.04809931  0.05999205]
 [ 0.10293583 -0.00734662 -0.05361217  0.06810268]
 [ 0.10180911 -0.00590198 -0.05906764  0.07644707]
 [ 0.10057322 -0.00428605 -0.06452971  0.08524515]], u = [[-0.1397108 ]
 [-0.09073908]
 [-0.06412135]
 [-0.04961342]
 [-0.04170053]
 [-0.03741803]
 [-0.0351568 ]
 [-0.03402508]
 [-0.03349731]
 [-0.03326601]]
iteration 1770 x = [[ 0.10057322 -0.00428605 -0.06452971  0.08524515]
 [ 0.09938462 -0.00285906 -0.05436939  0.05780635]
 [ 0.09838317 -0.00192835 -0.04580377  0.03552791]
 [ 0.09754493 -0.00141323 -0.03804295  0.0161818 ]
 [ 0.09685797 -0.00126773 -0.03067023 -0

iteration 1920 x = [[ 0.08460121 -0.00593118  0.09961045 -0.11253795]
 [ 0.0863996  -0.00771103  0.08028789 -0.06598046]
 [ 0.08786621 -0.00871069  0.06641083 -0.03432639]
 [ 0.08908479 -0.00916085  0.05547306 -0.01091324]
 [ 0.09010065 -0.00918953  0.04613023  0.00789999]
 [ 0.09093844 -0.00886831  0.03766015  0.02413226]
 [ 0.09161169 -0.00823714  0.02967077  0.03893778]
 [ 0.0921278  -0.00731753  0.02194366  0.05301235]
 [ 0.09249077 -0.00611954  0.01435299  0.06680505]
 [ 0.09270259 -0.00464573  0.00682589  0.08062342]
 [ 0.09276414 -0.00289338 -0.00067714  0.09468691]], u = [[-0.10326419]
 [-0.07538398]
 [-0.06051395]
 [-0.05257318]
 [-0.04830835]
 [-0.04599636]
 [-0.04473358]
 [-0.04404011]
 [-0.04364159]
 [-0.04336441]]
iteration 1930 x = [[ 0.09276414 -0.00289338 -0.00067714  0.09468691]
 [ 0.09293748 -0.00147444  0.01795582  0.04770565]
 [ 0.0934195  -0.0008237   0.03021306  0.01766055]
 [ 0.0941123  -0.00068092  0.03904732 -0.00321107]
 [ 0.0949634  -0.0009054   0.0460514  -0

iteration 2070 x = [[ 0.10662392  0.00236427 -0.07020572  0.09346326]
 [ 0.1053985   0.00380282 -0.0523883   0.0508601 ]
 [ 0.1044783   0.00452916 -0.03966408  0.02206597]
 [ 0.10378505  0.00475645 -0.02968272  0.00084633]
 [ 0.10327658  0.00460163 -0.02117766 -0.01621534]
 [ 0.10293026  0.0041286  -0.01346226 -0.03102408]
 [ 0.1027341   0.00337133 -0.00615821 -0.0446782 ]
 [ 0.102682    0.0023462   0.00094702 -0.0578403 ]
 [ 0.10277117  0.00105887  0.00797241 -0.07092729]
 [ 0.10300064 -0.00049186  0.01497896 -0.08420565]
 [ 0.10337026 -0.00231153  0.02198962 -0.09784564]], u = [[0.09567759]
 [0.06950283]
 [0.05553926]
 [0.04811443]
 [0.04419566]
 [0.04217323]
 [0.04118286]
 [0.04073693]
 [0.04053164]
 [0.04036574]]
iteration 2080 x = [[ 0.10337026 -0.00231153  0.02198962 -0.09784564]
 [ 0.10360436 -0.00375697  0.00147998 -0.04722784]
 [ 0.10350128 -0.00438397 -0.01175482 -0.01577269]
 [ 0.10317291 -0.00448705 -0.02106257  0.00529587]
 [ 0.10267963 -0.00422557 -0.0282539   0.02076238]

iteration 2230 x = [[ 0.14299703  0.00350974 -0.04151222  0.12854169]
 [ 0.14245111  0.0053954  -0.01315921  0.060729  ]
 [ 0.14236654  0.00620303  0.00465869  0.02042048]
 [ 0.14258104  0.00635532  0.01676721 -0.00498407]
 [ 0.14300664  0.00608103  0.02577973 -0.02234153]
 [ 0.14359568  0.00550308  0.0331188  -0.03541465]
 [ 0.14432255  0.00468593  0.0395669  -0.04630113]
 [ 0.14517381  0.00366124  0.04556088 -0.0561986 ]
 [ 0.14614284  0.00244171  0.05134621 -0.06580723]
 [ 0.14722682  0.00102895  0.05705739 -0.07554114]
 [ 0.14842497 -0.0005821   0.0627657  -0.08565367]], u = [[0.15294158]
 [0.09793717]
 [0.06815101]
 [0.05199785]
 [0.04324334]
 [0.03853833]
 [0.03607511]
 [0.03485207]
 [0.03428662]
 [0.03404515]]
iteration 2240 x = [[ 0.14842497 -0.0005821   0.0627657  -0.08565367]
 [ 0.14956433 -0.00199126  0.05121075 -0.05563189]
 [ 0.15049584 -0.00287018  0.04196984 -0.03252482]
 [ 0.15125462 -0.0033263   0.03392912 -0.0132788 ]
 [ 0.15185868 -0.00341964  0.02649337  0.00380686]

iteration 2390 x = [[ 1.80117929e-01  1.97026014e-04 -6.68020436e-02  8.86683534e-02]
 [ 1.78901281e-01  1.67114472e-03 -5.49038877e-02  5.91173630e-02]
 [ 1.77898172e-01  2.62738108e-03 -4.54365670e-02  3.67729112e-02]
 [ 1.77071760e-01  3.17754690e-03 -3.72264885e-02  1.84385156e-02]
 [ 1.76403257e-01  3.38377504e-03 -2.96401712e-02  2.32710037e-03]
 [ 1.75883667e-01  3.28006695e-03 -2.23310807e-02 -1.25959376e-02]
 [ 1.75509390e-01  2.88380570e-03 -1.51051668e-02 -2.69625558e-02]
 [ 1.75279869e-01  2.20199295e-03 -7.85244227e-03 -4.11816782e-02]
 [ 1.75196224e-01  1.23482909e-03 -5.14609148e-04 -5.55262286e-02]
 [ 1.75260369e-01 -2.19792887e-05  6.92933361e-03 -7.01738372e-02]
 [ 1.75474376e-01 -1.57563033e-03  1.44744029e-02 -8.52381238e-02]], u = [[0.06288377]
 [0.05087751]
 [0.04490861]
 [0.04215379]
 [0.04111591]
 [0.04100156]
 [0.04137414]
 [0.04196428]
 [0.04257535]
 [0.04306841]]
iteration 2400 x = [[ 0.17547438 -0.00157563  0.0144744  -0.08523812]
 [ 0.17560594 -0.00288204 -

iteration 2550 x = [[ 0.15026374  0.00305045  0.00144335  0.10110067]
 [ 0.15054409  0.00447072  0.02652553  0.04151968]
 [ 0.15123014  0.00494999  0.04204377  0.00671862]
 [ 0.1521746   0.00486834  0.05238375 -0.01472991]
 [ 0.15329772  0.00443006  0.05992011 -0.02903517]
 [ 0.15455638  0.00374368  0.06594379 -0.03959341]
 [ 0.15592744  0.0028651   0.07116357 -0.04828866]
 [ 0.1573988   0.00182076  0.07597609 -0.05619342]
 [ 0.1589646   0.00062005  0.08060944 -0.06394226]
 [ 0.16062259 -0.00073781  0.0851963  -0.07192363]
 [ 0.16237259 -0.00225993  0.08981257 -0.08038217]], u = [[0.13598003]
 [0.08590064]
 [0.05875785]
 [0.04401818]
 [0.0360064 ]
 [0.03167455]
 [0.02938908]
 [0.02826791]
 [0.02781039]
 [0.02771665]]
iteration 2560 x = [[ 0.16237259 -0.00225993  0.08981257 -0.08038217]
 [ 0.16407823 -0.00363285  0.08078576 -0.05722481]
 [ 0.16561262 -0.00457767  0.07268059 -0.03750276]
 [ 0.16698944 -0.00514886  0.06502229 -0.01980779]
 [ 0.16821511 -0.00537871  0.0575617  -0.00332598]

iteration 2710 x = [[ 0.18881381 -0.00587675 -0.03233251  0.05096053]
 [ 0.18821045 -0.00499416 -0.02802434  0.03749012]
 [ 0.18769633 -0.00438024 -0.02340573  0.02406571]
 [ 0.18727688 -0.00403349 -0.01855404  0.01074404]
 [ 0.18695629 -0.003952   -0.01351722 -0.0024882 ]
 [ 0.18673799 -0.00413461 -0.00832222 -0.0156925 ]
 [ 0.18662503 -0.00458171 -0.00298068 -0.02896408]
 [ 0.18662031 -0.00529578  0.00250464 -0.04241665]
 [ 0.18672668 -0.00628159  0.00813148 -0.05616309]
 [ 0.1869469  -0.00754598  0.01389133 -0.07030069]
 [ 0.18728345 -0.00909758  0.01976833 -0.08490997]], u = [[0.02065387]
 [0.02295501]
 [0.02474659]
 [0.02618718]
 [0.0273915 ]
 [0.028444  ]
 [0.02939479]
 [0.03024792]
 [0.03097014]
 [0.03152119]]
iteration 2720 x = [[ 0.18728345 -0.00909758  0.01976833 -0.08490997]
 [ 0.18743349 -0.01022588 -0.00470335 -0.02846138]
 [ 0.18718554 -0.01046293 -0.02005997  0.00448384]
 [ 0.1866802  -0.01016926 -0.03045966  0.02475989]
 [ 0.18599395 -0.00953862 -0.03815941  0.03826661]

iteration 2870 x = [[ 1.61626329e-01 -4.47196254e-04 -1.78033582e-02  1.14989776e-01]
 [ 1.61482905e-01  1.32237447e-03  3.39698476e-03  6.25432479e-02]
 [ 1.61697282e-01  2.22290653e-03  1.80009771e-02  2.78633399e-02]
 [ 1.62168218e-01  2.52802629e-03  2.90675931e-02  2.86812905e-03]
 [ 1.62841482e-01  2.38683056e-03  3.82429052e-02 -1.68537232e-02]
 [ 1.63688150e-01  1.88014750e-03  4.64142834e-02 -3.37395631e-02]
 [ 1.64692978e-01  1.05075376e-03  5.40636147e-02 -4.91690430e-02]
 [ 1.65848189e-01 -8.04365350e-05  6.14563492e-02 -6.39552564e-02]
 [ 1.67150141e-01 -1.50566278e-03  6.87409015e-02 -7.86041173e-02]
 [ 1.68597497e-01 -3.22553420e-03  7.59996806e-02 -9.34488498e-02]
 [ 1.70190192e-01 -5.24634543e-03  8.32777923e-02 -1.08726077e-01]], u = [[0.1132124 ]
 [0.07920726]
 [0.06111928]
 [0.05155081]
 [0.04653171]
 [0.04394223]
 [0.04265247]
 [0.04205213]
 [0.0417966 ]
 [0.04169045]]
iteration 2880 x = [[ 1.70190192e-01 -5.24634543e-03  8.32777923e-02 -1.08726077e-01]
 [ 1.716482

iteration 3030 x = [[ 2.49690404e-01 -1.71903619e-03  1.09768955e-02  9.76138164e-02]
 [ 2.50133396e-01 -3.23373972e-04  3.32600495e-02  4.25095347e-02]
 [ 2.50944980e-01  1.74806144e-04  4.78627645e-02  7.62169475e-03]
 [ 2.52007157e-01  8.56480108e-05  5.83349902e-02 -1.63665032e-02]
 [ 2.53256541e-01 -4.24166875e-04  6.65928407e-02 -3.45310228e-02]
 [ 2.54659247e-01 -1.26639073e-03  7.36733680e-02 -4.96644573e-02]
 [ 2.56197407e-01 -2.39623933e-03  8.01425227e-02 -6.33342278e-02]
 [ 2.57861947e-01 -3.79365260e-03  8.63148038e-02 -7.64527769e-02]
 [ 2.59648706e-01 -5.45319799e-03  9.23670824e-02 -8.95746067e-02]
 [ 2.61556265e-01 -7.37847947e-03  9.83974866e-02 -1.03051313e-01]
 [ 2.63584716e-01 -9.57896855e-03  1.04458657e-01 -1.17119519e-01]], u = [[0.11930712]
 [0.079344  ]
 [0.05789837]
 [0.04641322]
 [0.04028588]
 [0.03705094]
 [0.03539336]
 [0.03459306]
 [0.03423667]
 [0.03408375]]
iteration 3040 x = [[ 0.26358472 -0.00957897  0.10445866 -0.11711952]
 [ 0.26547331 -0.01145006  

iteration 3190 x = [[ 2.46547599e-01  3.05559611e-04 -2.95117029e-02  7.30223756e-02]
 [ 2.46127595e-01  1.35169188e-03 -1.25352902e-02  3.20066105e-02]
 [ 2.45998945e-01  1.70811356e-03 -3.57985696e-04  3.88367176e-03]
 [ 2.46088103e-01  1.57272142e-03  9.25665564e-03 -1.72776297e-02]
 [ 2.46355919e-01  1.05184600e-03  1.75150432e-02 -3.47322057e-02]
 [ 2.46781836e-01  2.01236670e-04  2.50718850e-02 -5.02992285e-02]
 [ 2.47355444e-01 -9.51987308e-04  3.22880430e-02 -6.50312324e-02]
 [ 2.48071970e-01 -2.39759483e-03  3.93670212e-02 -7.95693178e-02]
 [ 2.48929835e-01 -4.13586843e-03  4.64248394e-02 -9.43265390e-02]
 [ 2.49929240e-01 -6.17395960e-03  5.35238270e-02 -1.09578470e-01]
 [ 2.51071294e-01 -8.52368322e-03  6.06925451e-02 -1.25516984e-01]], u = [[0.09122427]
 [0.06647535]
 [0.05334736]
 [0.04644762]
 [0.04288954]
 [0.0411372 ]
 [0.04036889]
 [0.04012733]
 [0.04013002]
 [0.0401972 ]]
iteration 3200 x = [[ 0.25107129 -0.00852368  0.06069255 -0.12551698]
 [ 0.25200328 -0.01036332  

iteration 3350 x = [[ 0.15209117  0.00383196 -0.07053233  0.10507284]
 [ 0.15087207  0.00547576 -0.05143437  0.05981775]
 [ 0.14997226  0.00638333 -0.03858122  0.03124738]
 [ 0.14929558  0.00681218 -0.0291086   0.01182865]
 [ 0.14878994  0.00690381 -0.02146996 -0.00254725]
 [ 0.14842706  0.00673616 -0.01482646 -0.01414683]
 [ 0.14819167  0.00635184 -0.00871807 -0.02424769]
 [ 0.14807563  0.0057733  -0.00288801 -0.03359475]
 [ 0.14807484  0.00501105  0.00280887 -0.04263963]
 [ 0.14818744  0.00406829  0.00845288 -0.05166426]
 [ 0.14841281  0.00294358  0.01408683 -0.0608532 ]], u = [[0.10290224]
 [0.07060066]
 [0.05322745]
 [0.04388449]
 [0.03886919]
 [0.03620194]
 [0.0348222 ]
 [0.03414801]
 [0.03384092]
 [0.03370461]]
iteration 3360 x = [[ 0.14841281  0.00294358  0.01408683 -0.0608532 ]
 [ 0.14862146  0.00193828  0.00680638 -0.03993688]
 [ 0.14869712  0.00131072  0.00078144 -0.02300999]
 [ 0.14865853  0.00099912 -0.00462456 -0.00829184]
 [ 0.14851468  0.00096942 -0.00974927  0.00521791]

iteration 3510 x = [[ 1.95961809e-01  6.71629109e-05  1.31792992e-02  8.85704087e-02]
 [ 1.96432435e-01  1.33165253e-03  3.38265455e-02  3.83855656e-02]
 [ 1.97240146e-01  1.79214643e-03  4.69131801e-02  7.94008358e-03]
 [ 1.98268626e-01  1.75151038e-03  5.59178129e-02 -1.18588718e-02]
 [ 1.99455123e-01  1.37262256e-03  6.27234494e-02 -2.59626766e-02]
 [ 2.00765946e-01  7.41854936e-04  6.83555651e-02 -3.70951471e-02]
 [ 2.02183313e-01 -9.68416636e-05  7.33813761e-02 -4.67878873e-02]
 [ 2.03698341e-01 -1.12371526e-03  7.81241039e-02 -5.59364357e-02]
 [ 2.05307279e-01 -2.33342721e-03  8.27742972e-02 -6.50906614e-02]
 [ 2.07009408e-01 -3.72961329e-03  8.74449727e-02 -7.46005601e-02]
 [ 2.08805769e-01 -5.32163904e-03  9.21991574e-02 -8.46906418e-02]], u = [[0.11122009]
 [0.07174894]
 [0.05044969]
 [0.03896566]
 [0.03280714]
 [0.0295764 ]
 [0.02799794]
 [0.02737821]
 [0.02731039]
 [0.0275296 ]]
iteration 3520 x = [[ 0.20880577 -0.00532164  0.09219916 -0.08469064]
 [ 0.21050137 -0.00665716  

iteration 3660 x = [[ 0.22376925 -0.00601046  0.03309651 -0.11749309]
 [ 0.2241834  -0.00776082  0.0083879  -0.05816942]
 [ 0.22419027 -0.00855541 -0.00766012 -0.02164652]
 [ 0.22392317 -0.00874487 -0.01902653  0.00249915]
 [ 0.22345414 -0.00851932 -0.02786342  0.01994723]
 [ 0.22282203 -0.00798112 -0.03534052  0.03382364]
 [ 0.22204759 -0.00718396 -0.04210094  0.04588295]
 [ 0.22114154 -0.00615391 -0.04850525  0.05714241]
 [ 0.22010893 -0.0049008  -0.05475894  0.06821468]
 [ 0.21895162 -0.00342454 -0.06097711  0.07947847]
 [ 0.21766972 -0.00171888 -0.06722085  0.09117517]], u = [[-0.13314674]
 [-0.08808308]
 [-0.06378799]
 [-0.05069539]
 [-0.04366328]
 [-0.03993715]
 [-0.0380404 ]
 [-0.03716268]
 [-0.03682999]
 [-0.03675757]]
iteration 3670 x = [[ 2.17669716e-01 -1.71887807e-03 -6.72208537e-02  9.11751652e-02]
 [ 2.16474620e-01 -2.74949629e-04 -5.23363713e-02  5.36479370e-02]
 [ 2.15541290e-01  5.20921150e-04 -4.10287582e-02  2.62270359e-02]
 [ 2.14815024e-01  8.25140541e-04 -3.162007

iteration 3800 x = [[ 0.15605412 -0.00458625  0.04861839 -0.08539427]
 [ 0.15686816 -0.00590873  0.0328324  -0.04727667]
 [ 0.15740825 -0.00658478  0.02120705 -0.02059848]
 [ 0.15773806 -0.00679067  0.0117941  -0.00016608]
 [ 0.15789129 -0.00662241  0.0035422   0.01688116]
 [ 0.15788542 -0.00613141 -0.00412086  0.03215437]
 [ 0.15772904 -0.00534361 -0.01151263  0.04659788]
 [ 0.15742576 -0.0042697  -0.01881375  0.06079625]
 [ 0.15697637 -0.00291076 -0.02612728  0.07513054]
 [ 0.15638006 -0.00126147 -0.03350796  0.08985732]
 [ 0.15563524  0.00068782 -0.04098041  0.10515766]], u = [[-0.0846318 ]
 [-0.06337853]
 [-0.0522291 ]
 [-0.04648991]
 [-0.04365591]
 [-0.04239784]
 [-0.04200223]
 [-0.04206422]
 [-0.0423304 ]
 [-0.04264084]]
iteration 3810 x = [[ 0.15563524  0.00068782 -0.04098041  0.10515766]
 [ 0.15501205  0.00230722 -0.02139783  0.057309  ]
 [ 0.15472169  0.00313004 -0.00767451  0.0252982 ]
 [ 0.15467425  0.0034003   0.00290745  0.00193176]
 [ 0.15482162  0.00325106  0.01181427 -0

iteration 3950 x = [[ 0.15434843  0.004144   -0.02418356  0.10874111]
 [ 0.15414603  0.00564955  0.00387047  0.04246665]
 [ 0.15440525  0.00609089  0.02201073  0.00201746]
 [ 0.1549732   0.00586479  0.0347638  -0.0244508 ]
 [ 0.15576665  0.00518585  0.04457095 -0.04337039]
 [ 0.15673989  0.00416949  0.05275044 -0.05825735]
 [ 0.15786756  0.00287665  0.06001909 -0.07106355]
 [ 0.15913544  0.00133762  0.06677414 -0.08290781]
 [ 0.16053554 -0.00043517  0.07324398 -0.09446719]
 [ 0.16206353 -0.00244046  0.07956585 -0.10618006]
 [ 0.1637173  -0.00468434  0.08582414 -0.11834791]], u = [[0.15210256]
 [0.10031393]
 [0.07216173]
 [0.05672411]
 [0.04812085]
 [0.04320405]
 [0.04030303]
 [0.03853629]
 [0.03742823]
 [0.03670212]]
iteration 3960 x = [[ 0.1637173  -0.00468434  0.08582414 -0.11834791]
 [ 0.1652434  -0.00658103  0.06684631 -0.07186646]
 [ 0.16644664 -0.00770437  0.05351639 -0.04081637]
 [ 0.16741382 -0.0082931   0.04322774 -0.01828758]
 [ 0.16819173 -0.00847952  0.03458052 -0.00050782]

iteration 4110 x = [[ 1.26267169e-01  3.08172880e-03 -2.01867212e-02  1.01448288e-01]
 [ 1.26113803e-01  4.51163694e-03  4.78346790e-03  4.21355954e-02]
 [ 1.26378612e-01  4.97109779e-03  2.16593118e-02  4.14372800e-03]
 [ 1.26937154e-01  4.78735230e-03  3.41733992e-02 -2.23376379e-02]
 [ 1.27722406e-01  4.13652009e-03  4.43406474e-02 -4.26593198e-02]
 [ 1.28698373e-01  3.11198941e-03  5.32515389e-02 -5.97701706e-02]
 [ 1.29845899e-01  1.76119948e-03  6.15013889e-02 -7.53306327e-02]
 [ 1.31155070e-01  1.05381845e-04  6.94198231e-02 -9.03089191e-02]
 [ 1.32621099e-01 -1.84975177e-03  7.71903372e-02 -1.05293240e-01]
 [ 1.34242017e-01 -4.10804573e-03  8.49116327e-02 -1.20653612e-01]
 [ 1.36017304e-01 -6.67941782e-03  9.26302444e-02 -1.36628965e-01]], u = [[0.13515834]
 [0.0930676 ]
 [0.07043608]
 [0.05826876]
 [0.05172603]
 [0.04821701]
 [0.04635232]
 [0.04536732]
 [0.04481658]
 [0.04442369]]
iteration 4120 x = [[ 0.1360173  -0.00667942  0.09263024 -0.13662897]
 [ 0.1376386  -0.00884897  

iteration 4260 x = [[ 0.09880171 -0.0020859   0.03071931 -0.09982927]
 [ 0.09924987 -0.00366264  0.01414974 -0.05831952]
 [ 0.09941434 -0.00454128  0.00233137 -0.02984833]
 [ 0.09936782 -0.00492278 -0.00696149 -0.00850194]
 [ 0.09914882 -0.00491696 -0.0149232   0.00895316]
 [ 0.09877754 -0.00458352 -0.02219481  0.02430991]
 [ 0.0982643  -0.00395408 -0.02912251  0.03859117]
 [ 0.09761409 -0.00304397 -0.03589621  0.05240962]
 [ 0.0968289  -0.00185848 -0.04262266  0.06615847]
 [ 0.09590908 -0.00039626 -0.04936257  0.08010953]
 [ 0.094854    0.00134879 -0.05615134  0.09446811]], u = [[-0.08793433]
 [-0.06363161]
 [-0.05088611]
 [-0.04429869]
 [-0.0409744 ]
 [-0.03937268]
 [-0.03867831]
 [-0.03845855]
 [-0.03847394]
 [-0.03859232]]
iteration 4270 x = [[ 0.094854    0.00134879 -0.05615134  0.09446811]
 [ 0.09390489  0.00281373 -0.03881153  0.05249192]
 [ 0.09325669  0.00356656 -0.02604187  0.02308968]
 [ 0.0928394   0.00380125 -0.01570976  0.00057281]
 [ 0.09261577  0.0036239  -0.00666825 -0

iteration 4420 x = [[ 0.09165776 -0.01288502  0.04204461 -0.12241743]
 [ 0.0921901  -0.01462075  0.0112687  -0.05186607]
 [ 0.09222169 -0.01524521 -0.00806673 -0.01095277]
 [ 0.09192896 -0.01521359 -0.02118395  0.01392876]
 [ 0.09140791 -0.01477182 -0.03091047  0.03016986]
 [ 0.09071095 -0.01405189 -0.03878244  0.04180886]
 [ 0.08986673 -0.01312327 -0.04564055  0.05107721]
 [ 0.08889086 -0.01202069 -0.05195073  0.05923183]
 [ 0.08779165 -0.01075907 -0.05797529  0.06700033]
 [ 0.08657334 -0.00934174 -0.06386395  0.07481878]
 [ 0.08523771 -0.00776484 -0.06970746  0.0829711 ]], u = [[-0.16828786]
 [-0.10838692]
 [-0.07579767]
 [-0.05797826]
 [-0.04816622]
 [-0.04272102]
 [-0.03968126]
 [-0.03798117]
 [-0.03703085]
 [-0.03652105]]
iteration 4430 x = [[ 0.08523771 -0.00776484 -0.06970746  0.0829711 ]
 [ 0.08391336 -0.00632273 -0.06276125  0.06154866]
 [ 0.08272975 -0.00530045 -0.0556281   0.04093858]
 [ 0.08169057 -0.00468382 -0.04831319  0.02093714]
 [ 0.08079928 -0.0044623  -0.04083497  0

iteration 4580 x = [[ 0.00256163 -0.00460607  0.01499733 -0.08015094]
 [ 0.00266164 -0.00572699 -0.00494315 -0.03241532]
 [ 0.0024298  -0.0060705  -0.01821072 -0.00219797]
 [ 0.00196868 -0.00590527 -0.02788441  0.01858111]
 [ 0.00133343 -0.00537542 -0.03563281  0.03433944]
 [ 0.0005534  -0.00455663 -0.04236652  0.04752433]
 [-0.00035615 -0.00348634 -0.04858947  0.0595248 ]
 [-0.00138787 -0.00218    -0.05458534  0.07115647]
 [-0.00253879 -0.00064002 -0.06051315  0.08291233]
 [-0.00380839  0.00113907 -0.06645436  0.09508834]
 [-0.00519728  0.00316751 -0.07244557  0.10786935]], u = [[-0.10767289]
 [-0.07292413]
 [-0.05423685]
 [-0.04422538]
 [-0.03892207]
 [-0.0361995 ]
 [-0.0349055 ]
 [-0.03438667]
 [-0.03423364]
 [-0.03420743]]
iteration 4590 x = [[-0.00519728  0.00316751 -0.07244557  0.10786935]
 [-0.00646403  0.00488552 -0.05428472  0.06443483]
 [-0.00742001  0.00587936 -0.04134922  0.03527187]
 [-0.00814545  0.00636961 -0.03121917  0.01396416]
 [-0.00868339  0.00647784 -0.022591   -0

iteration 4730 x = [[ 0.07382746 -0.00550355 -0.00510861  0.09590746]
 [ 0.07389871 -0.00404084  0.01217945  0.05085153]
 [ 0.07425958 -0.0033267   0.02387367  0.02086025]
 [ 0.07482433 -0.00312948  0.03258049 -0.00095423]
 [ 0.07554729 -0.00332367  0.039703   -0.01835424]
 [ 0.07640438 -0.00384202  0.04599847 -0.03342226]
 [ 0.0773832  -0.00464989  0.05188009 -0.04734348]
 [ 0.07847779 -0.00573148  0.05757885 -0.06082614]
 [ 0.07968583 -0.00708257  0.0632278  -0.07432143]
 [ 0.08100709 -0.00870646  0.06890297 -0.08813213]
 [ 0.08244248 -0.01061157  0.07464399 -0.10246864]], u = [[0.09073504]
 [0.06188923]
 [0.04660535]
 [0.03858226]
 [0.0344401 ]
 [0.03237992]
 [0.03145068]
 [0.03114168]
 [0.03115476]
 [0.0312979 ]]
iteration 4740 x = [[ 0.08244248 -0.01061157  0.07464399 -0.10246864]
 [ 0.08371936 -0.01216227  0.05310386 -0.05313292]
 [ 0.08463121 -0.0129032   0.03811728 -0.02127653]
 [ 0.0852789  -0.01310372  0.02667309  0.00103472]
 [ 0.08571694 -0.0129109   0.01714443  0.01813766]

iteration 4880 x = [[ 0.00532318 -0.00139514  0.01007262 -0.09458113]
 [ 0.00535273 -0.00285182 -0.00706548 -0.05155922]
 [ 0.00509582 -0.00360037 -0.01859263 -0.02358387]
 [ 0.00463847 -0.00387214 -0.02712242 -0.00376945]
 [ 0.00402646 -0.00379229 -0.03406619  0.01164685]
 [ 0.00328381 -0.00342769 -0.04019102  0.02475179]
 [ 0.00242265 -0.00281252 -0.04592125  0.03673805]
 [ 0.00144842 -0.00196192 -0.05149986  0.04832332]
 [ 0.00036274 -0.00087928 -0.0570701   0.05996416]
 [-0.00083506  0.00043947 -0.06271318  0.07195707]
 [-0.00214681  0.00200326 -0.06846655  0.0844894 ]], u = [[-0.09110406]
 [-0.06212125]
 [-0.04675277]
 [-0.03870368]
 [-0.03460257]
 [-0.03265788]
 [-0.03192319]
 [-0.03187829]
 [-0.03219741]
 [-0.03264817]]
iteration 4890 x = [[-0.00214681  0.00200326 -0.06846655  0.0844894 ]
 [-0.00334971  0.00329225 -0.05187182  0.0448409 ]
 [-0.00426398  0.003908   -0.0395861   0.01700719]
 [-0.00495571  0.00403279 -0.02960709 -0.00435509]
 [-0.0054602   0.00376628 -0.02085544 -0

# Rollouts

In [6]:
multi_evaluate(env, dynamics, x0s, us)

performance
receding_performance


rewards  lengths
performance              50.0       50
receding_performance   5000.0     5000